// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/proprdb/options.proto

package proprdbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto_proprdb_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "proprdb.external",
		Tag:           "varint,50001,opt,name=external",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "proprdb.omit_table",
		Tag:           "varint,50002,opt,name=omit_table",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "proprdb.omit_sync",
		Tag:           "varint,50003,opt,name=omit_sync",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "proprdb.validate_write",
		Tag:           "varint,50004,opt,name=validate_write",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "proprdb.allow_custom_id_insert",
		Tag:           "varint,50005,opt,name=allow_custom_id_insert",
		Filename:      "proto/proprdb/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool external = 50001;
	E_External = &file_proto_proprdb_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool omit_table = 50002;
	E_OmitTable = &file_proto_proprdb_options_proto_extTypes[1]
	// optional bool omit_sync = 50003;
	E_OmitSync = &file_proto_proprdb_options_proto_extTypes[2]
	// optional bool validate_write = 50004;
	E_ValidateWrite = &file_proto_proprdb_options_proto_extTypes[3]
	// optional bool allow_custom_id_insert = 50005;
	E_AllowCustomIdInsert = &file_proto_proprdb_options_proto_extTypes[4]
)

var File_proto_proprdb_options_proto protoreflect.FileDescriptor

const file_proto_proprdb_options_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/proprdb/options.proto\x12\aproprdb\x1a google/protobuf/descriptor.proto:;\n" +
	"\bexternal\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\bexternal:@\n" +
	"\n" +
	"omit_table\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\bR\tomitTable:>\n" +
	"\tomit_sync\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\bR\bomitSync:H\n" +
	"\x0evalidate_write\x12\x1f.google.protobuf.MessageOptions\x18Ԇ\x03 \x01(\bR\rvalidateWrite:V\n" +
	"\x16allow_custom_id_insert\x12\x1f.google.protobuf.MessageOptions\x18Ն\x03 \x01(\bR\x13allowCustomIdInsertB3Z1github.com/fingon/proprdb/proto/proprdb;proprdbpbb\x06proto3"

var file_proto_proprdb_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),   // 0: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_proto_proprdb_options_proto_depIdxs = []int32{
	0, // 0: proprdb.external:extendee -> google.protobuf.FieldOptions
	1, // 1: proprdb.omit_table:extendee -> google.protobuf.MessageOptions
	1, // 2: proprdb.omit_sync:extendee -> google.protobuf.MessageOptions
	1, // 3: proprdb.validate_write:extendee -> google.protobuf.MessageOptions
	1, // 4: proprdb.allow_custom_id_insert:extendee -> google.protobuf.MessageOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	0, // [0:5] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proprdb_options_proto_init() }
func file_proto_proprdb_options_proto_init() {
	if File_proto_proprdb_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proprdb_options_proto_rawDesc), len(file_proto_proprdb_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_proto_proprdb_options_proto_goTypes,
		DependencyIndexes: file_proto_proprdb_options_proto_depIdxs,
		ExtensionInfos:    file_proto_proprdb_options_proto_extTypes,
	}.Build()
	File_proto_proprdb_options_proto = out.File
	file_proto_proprdb_options_proto_goTypes = nil
	file_proto_proprdb_options_proto_depIdxs = nil
}
