// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/proprdb/options.proto

package proprdbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_proto_proprdb_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proprdb_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_proto_proprdb_options_proto_rawDescGZIP(), []int{0}
}

func (x *Index) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var file_proto_proprdb_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "com.github.fingon.proprdb.external",
		Tag:           "varint,50001,opt,name=external",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "com.github.fingon.proprdb.omit_table",
		Tag:           "varint,50002,opt,name=omit_table",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "com.github.fingon.proprdb.omit_sync",
		Tag:           "varint,50003,opt,name=omit_sync",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "com.github.fingon.proprdb.validate_write",
		Tag:           "varint,50004,opt,name=validate_write",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "com.github.fingon.proprdb.allow_custom_id_insert",
		Tag:           "varint,50005,opt,name=allow_custom_id_insert",
		Filename:      "proto/proprdb/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]*Index)(nil),
		Field:         50006,
		Name:          "com.github.fingon.proprdb.indexes",
		Tag:           "bytes,50006,rep,name=indexes",
		Filename:      "proto/proprdb/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool external = 50001;
	E_External = &file_proto_proprdb_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool omit_table = 50002;
	E_OmitTable = &file_proto_proprdb_options_proto_extTypes[1]
	// optional bool omit_sync = 50003;
	E_OmitSync = &file_proto_proprdb_options_proto_extTypes[2]
	// optional bool validate_write = 50004;
	E_ValidateWrite = &file_proto_proprdb_options_proto_extTypes[3]
	// optional bool allow_custom_id_insert = 50005;
	E_AllowCustomIdInsert = &file_proto_proprdb_options_proto_extTypes[4]
	// repeated com.github.fingon.proprdb.Index indexes = 50006;
	E_Indexes = &file_proto_proprdb_options_proto_extTypes[5]
)

var File_proto_proprdb_options_proto protoreflect.FileDescriptor

const file_proto_proprdb_options_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/proprdb/options.proto\x12\x19com.github.fingon.proprdb\x1a google/protobuf/descriptor.proto\"\x1f\n" +
	"\x05Index\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields:;\n" +
	"\bexternal\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\bexternal:@\n" +
	"\n" +
	"omit_table\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\bR\tomitTable:>\n" +
	"\tomit_sync\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\bR\bomitSync:H\n" +
	"\x0evalidate_write\x12\x1f.google.protobuf.MessageOptions\x18Ԇ\x03 \x01(\bR\rvalidateWrite:V\n" +
	"\x16allow_custom_id_insert\x12\x1f.google.protobuf.MessageOptions\x18Ն\x03 \x01(\bR\x13allowCustomIdInsert:]\n" +
	"\aindexes\x12\x1f.google.protobuf.MessageOptions\x18ֆ\x03 \x03(\v2 .com.github.fingon.proprdb.IndexR\aindexesB3Z1github.com/fingon/proprdb/proto/proprdb;proprdbpbb\x06proto3"

var (
	file_proto_proprdb_options_proto_rawDescOnce sync.Once
	file_proto_proprdb_options_proto_rawDescData []byte
)

func file_proto_proprdb_options_proto_rawDescGZIP() []byte {
	file_proto_proprdb_options_proto_rawDescOnce.Do(func() {
		file_proto_proprdb_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proprdb_options_proto_rawDesc), len(file_proto_proprdb_options_proto_rawDesc)))
	})
	return file_proto_proprdb_options_proto_rawDescData
}

var file_proto_proprdb_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_proprdb_options_proto_goTypes = []any{
	(*Index)(nil),                       // 0: com.github.fingon.proprdb.Index
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_proto_proprdb_options_proto_depIdxs = []int32{
	1, // 0: com.github.fingon.proprdb.external:extendee -> google.protobuf.FieldOptions
	2, // 1: com.github.fingon.proprdb.omit_table:extendee -> google.protobuf.MessageOptions
	2, // 2: com.github.fingon.proprdb.omit_sync:extendee -> google.protobuf.MessageOptions
	2, // 3: com.github.fingon.proprdb.validate_write:extendee -> google.protobuf.MessageOptions
	2, // 4: com.github.fingon.proprdb.allow_custom_id_insert:extendee -> google.protobuf.MessageOptions
	2, // 5: com.github.fingon.proprdb.indexes:extendee -> google.protobuf.MessageOptions
	0, // 6: com.github.fingon.proprdb.indexes:type_name -> com.github.fingon.proprdb.Index
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	6, // [6:7] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proprdb_options_proto_init() }
func file_proto_proprdb_options_proto_init() {
	if File_proto_proprdb_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proprdb_options_proto_rawDesc), len(file_proto_proprdb_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_proto_proprdb_options_proto_goTypes,
		DependencyIndexes: file_proto_proprdb_options_proto_depIdxs,
		MessageInfos:      file_proto_proprdb_options_proto_msgTypes,
		ExtensionInfos:    file_proto_proprdb_options_proto_extTypes,
	}.Build()
	File_proto_proprdb_options_proto = out.File
	file_proto_proprdb_options_proto_goTypes = nil
	file_proto_proprdb_options_proto_depIdxs = nil
}
