// Code generated by protoc-gen-proprdb-rust. DO NOT EDIT.
const DESCRIPTOR_BYTES: &[u8] = b"\x0a\xde\x01\x0a\x0c\x73\x79\x73\x74\x65\x6d\x2e\x70\x72\x6f\x74\x6f\x12\x15\x67\x65\x6e\x65\x72\x61\x74\x65\x64\x74\x65\x73\x74\x2e\x65\x78\x61\x6d\x70\x6c\x65\x22\x2e\x0a\x06\x50\x65\x72\x73\x6f\x6e\x12\x12\x0a\x04\x6e\x61\x6d\x65\x18\x01\x20\x01\x28\x09\x52\x04\x6e\x61\x6d\x65\x12\x10\x0a\x03\x61\x67\x65\x18\x02\x20\x01\x28\x03\x52\x03\x61\x67\x65\x22\x1a\x0a\x04\x4e\x6f\x74\x65\x12\x12\x0a\x04\x74\x65\x78\x74\x18\x01\x20\x01\x28\x09\x52\x04\x74\x65\x78\x74\x22\x45\x0a\x06\x43\x68\x6f\x69\x63\x65\x12\x16\x0a\x05\x6c\x61\x62\x65\x6c\x18\x01\x20\x01\x28\x09\x48\x00\x52\x05\x6c\x61\x62\x65\x6c\x12\x16\x0a\x05\x63\x6f\x75\x6e\x74\x18\x02\x20\x01\x28\x03\x48\x00\x52\x05\x63\x6f\x75\x6e\x74\x42\x0b\x0a\x09\x73\x65\x6c\x65\x63\x74\x69\x6f\x6e\x22\x1c\x0a\x06\x48\x69\x64\x64\x65\x6e\x12\x12\x0a\x04\x74\x65\x78\x74\x18\x01\x20\x01\x28\x09\x52\x04\x74\x65\x78\x74\x62\x06\x70\x72\x6f\x74\x6f\x33";
fn descriptor_pool() -> ::proprdb_runtime::Result<::proprdb_runtime::DescriptorPool> {
static POOL: ::std::sync::OnceLock<::proprdb_runtime::DescriptorPool> = ::std::sync::OnceLock::new();
if let Some(pool) = POOL.get() { return Ok(pool.clone()); }
let pool = ::proprdb_runtime::DescriptorPool::decode(DESCRIPTOR_BYTES)?;
Ok(POOL.get_or_init(|| pool).clone()) }
pub struct PersonModel;
pub type PersonRow = ::proprdb_runtime::Row<crate::generatedtest::example::Person>;
pub type PersonTable<'a> = ::proprdb_runtime::Table<'a, PersonModel>;
impl ::proprdb_runtime::Model for PersonModel {
type Data = crate::generatedtest::example::Person;
fn descriptor() -> ::proprdb_runtime::Result<::proprdb_runtime::MessageDescriptor> { descriptor_pool()?.get_message_by_name(Self::TYPE_NAME).ok_or_else(|| ::proprdb_runtime::Error::Invalid(format!("missing descriptor {}", Self::TYPE_NAME))) }
const TABLE_NAME: &str = "generatedtest_example_person";
const TYPE_NAME: &str = "generatedtest.example.Person";
const PROJECTION_SCHEMA: &str = "name:string;age:int64";
const CREATE_TABLE_SQL: &str = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_person\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"name\" TEXT NOT NULL DEFAULT '', \"age\" INTEGER NOT NULL DEFAULT 0)";
const INSERT_SQL: &str = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?)";
const UPSERT_SQL: &str = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"name\" = excluded.\"name\", \"age\" = excluded.\"age\"";
const INDEX_PREFIX: &str = "idx_generatedtest_example_person__";
const SYNC_ENABLED: bool = true;
const CHANGE_LISTENERS: bool = true;
const QUERY_STATISTICS: bool = true;
const COLUMNS: &[::proprdb_runtime::Column] = &[
::proprdb_runtime::Column { name: "name", definition: "\"name\" TEXT NOT NULL DEFAULT ''", legacy_oneof_presence_repair: false },
::proprdb_runtime::Column { name: "age", definition: "\"age\" INTEGER NOT NULL DEFAULT 0", legacy_oneof_presence_repair: false },
];
const INDEXES: &[&str] = &[
"CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name\" ON \"generatedtest_example_person\" (\"name\")",
"CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name_age\" ON \"generatedtest_example_person\" (\"name\", \"age\")",
];
fn validate(data: &Self::Data) -> ::proprdb_runtime::Result<()> { data.valid() }
fn projected_values(data: &Self::Data) -> Vec<::proprdb_runtime::Value> { vec![
::proprdb_runtime::Value::Text(data.name.clone()),
::proprdb_runtime::Value::Integer(data.age),
] }
}
impl ::proprdb_runtime::CustomIdModel for PersonModel {}
pub struct NoteModel;
pub type NoteRow = ::proprdb_runtime::Row<crate::generatedtest::example::Note>;
pub type NoteTable<'a> = ::proprdb_runtime::Table<'a, NoteModel>;
impl ::proprdb_runtime::Model for NoteModel {
type Data = crate::generatedtest::example::Note;
fn descriptor() -> ::proprdb_runtime::Result<::proprdb_runtime::MessageDescriptor> { descriptor_pool()?.get_message_by_name(Self::TYPE_NAME).ok_or_else(|| ::proprdb_runtime::Error::Invalid(format!("missing descriptor {}", Self::TYPE_NAME))) }
const TABLE_NAME: &str = "generatedtest_example_note";
const TYPE_NAME: &str = "generatedtest.example.Note";
const PROJECTION_SCHEMA: &str = "text:string";
const CREATE_TABLE_SQL: &str = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_note\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"text\" TEXT NOT NULL DEFAULT '')";
const INSERT_SQL: &str = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?)";
const UPSERT_SQL: &str = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"text\" = excluded.\"text\"";
const INDEX_PREFIX: &str = "idx_generatedtest_example_note__";
const SYNC_ENABLED: bool = false;
const CHANGE_LISTENERS: bool = true;
const QUERY_STATISTICS: bool = false;
const COLUMNS: &[::proprdb_runtime::Column] = &[
::proprdb_runtime::Column { name: "text", definition: "\"text\" TEXT NOT NULL DEFAULT ''", legacy_oneof_presence_repair: false },
];
const INDEXES: &[&str] = &[
];
fn projected_values(data: &Self::Data) -> Vec<::proprdb_runtime::Value> { vec![
::proprdb_runtime::Value::Text(data.text.clone()),
] }
}
pub struct ChoiceModel;
pub type ChoiceRow = ::proprdb_runtime::Row<crate::generatedtest::example::Choice>;
pub type ChoiceTable<'a> = ::proprdb_runtime::Table<'a, ChoiceModel>;
impl ::proprdb_runtime::Model for ChoiceModel {
type Data = crate::generatedtest::example::Choice;
fn descriptor() -> ::proprdb_runtime::Result<::proprdb_runtime::MessageDescriptor> { descriptor_pool()?.get_message_by_name(Self::TYPE_NAME).ok_or_else(|| ::proprdb_runtime::Error::Invalid(format!("missing descriptor {}", Self::TYPE_NAME))) }
const TABLE_NAME: &str = "generatedtest_example_choice";
const TYPE_NAME: &str = "generatedtest.example.Choice";
const PROJECTION_SCHEMA: &str = "label:string:optional";
const CREATE_TABLE_SQL: &str = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_choice\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"label\" TEXT)";
const INSERT_SQL: &str = "INSERT INTO \"generatedtest_example_choice\" (\"id\", \"at_ns\", \"data\", \"label\") VALUES (?, ?, ?, ?)";
const UPSERT_SQL: &str = "INSERT INTO \"generatedtest_example_choice\" (\"id\", \"at_ns\", \"data\", \"label\") VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"label\" = excluded.\"label\"";
const INDEX_PREFIX: &str = "idx_generatedtest_example_choice__";
const SYNC_ENABLED: bool = true;
const CHANGE_LISTENERS: bool = false;
const QUERY_STATISTICS: bool = false;
const COLUMNS: &[::proprdb_runtime::Column] = &[
::proprdb_runtime::Column { name: "label", definition: "\"label\" TEXT", legacy_oneof_presence_repair: true },
];
const INDEXES: &[&str] = &[
];
fn projected_values(data: &Self::Data) -> Vec<::proprdb_runtime::Value> { vec![
match &data.selection { Some(crate::generatedtest::example::choice::Selection::Label(value)) => ::proprdb_runtime::Value::Text(value.clone()), _ => ::proprdb_runtime::Value::Null },
] }
}
pub struct Crud<'a> {
pub person: ::proprdb_runtime::Table<'a, PersonModel>,
pub note: ::proprdb_runtime::Table<'a, NoteModel>,
pub choice: ::proprdb_runtime::Table<'a, ChoiceModel>,
}
impl<'a> Crud<'a> {
pub fn new(connection: &'a ::proprdb_runtime::Connection) -> Self { Self {
person: ::proprdb_runtime::Table::new(connection),
note: ::proprdb_runtime::Table::new(connection),
choice: ::proprdb_runtime::Table::new(connection),
} }
fn tables(&self) -> Vec<&dyn ::proprdb_runtime::SyncTable> { vec![
&self.person,
&self.note,
&self.choice,
] }
pub fn initialize(&self) -> ::proprdb_runtime::Result<()> { ::proprdb_runtime::initialize_tables(&self.tables()) }
pub fn read_jsonl(&self, remote: &str, reader: impl ::std::io::BufRead) -> ::proprdb_runtime::Result<()> { ::proprdb_runtime::read_jsonl(&self.tables(), remote, reader) }
pub fn prepare_jsonl(&self, remote: &str, writer: impl ::std::io::Write) -> ::proprdb_runtime::Result<::proprdb_runtime::JsonlCheckpoint> { ::proprdb_runtime::prepare_jsonl(&self.tables(), remote, writer) }
pub fn write_jsonl(&self, remote: &str, writer: impl ::std::io::Write) -> ::proprdb_runtime::Result<()> { ::proprdb_runtime::write_jsonl(&self.tables(), remote, writer) }
pub fn acknowledge_jsonl(&self, checkpoint: &::proprdb_runtime::JsonlCheckpoint) -> ::proprdb_runtime::Result<()> { ::proprdb_runtime::acknowledge_jsonl(::proprdb_runtime::SyncTable::connection(&self.person), checkpoint) }
pub fn discard_jsonl(&self, checkpoint: &::proprdb_runtime::JsonlCheckpoint) -> ::proprdb_runtime::Result<()> { ::proprdb_runtime::discard_jsonl(::proprdb_runtime::SyncTable::connection(&self.person), checkpoint) }
pub fn introspect_tables(&self) -> ::proprdb_runtime::Result<Vec<::proprdb_runtime::TableIntrospection>> { ::proprdb_runtime::SyncTable::introspect_all(&self.person, &self.tables()) }
}
