// Code generated by protoc-gen-proprdb-swift. DO NOT EDIT.

import Foundation
import SwiftProtobuf
import ProprDBSwiftRuntime

let PersonTableName = "generatedtest_example_person"
private let PersonTableNameQuoted = quoteSQLiteIdentifier(PersonTableName)
let PersonTypeName = "generatedtest.example.Person"
let PersonProjectionSchema = "name:string;age:int64"
private let PersonCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_person\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"name\" TEXT NOT NULL DEFAULT '', \"age\" INTEGER NOT NULL DEFAULT 0)"
private let PersonInsertSQL = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?)"
private let PersonUpsertSQL = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"name\" = excluded.\"name\", \"age\" = excluded.\"age\""
private let PersonGeneratedIndexPrefix = "idx_generatedtest_example_person__"
private let PersonCreateIndexSQL1 = "CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name\" ON \"generatedtest_example_person\" (\"name\")"
private let PersonCreateIndexSQL2 = "CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name_age\" ON \"generatedtest_example_person\" (\"name\", \"age\")"
private let PersonReprojectSQL = "UPDATE \"generatedtest_example_person\" SET \"name\" = ?, \"age\" = ? WHERE id = ?"

private let PersonGeneratedBinding = GeneratedTableBinding(
	descriptor: GeneratedTableDescriptor(tableName: PersonTableName, typeName: PersonTypeName, isCore: false, syncEnabled: true, changeListenersEnabled: true),
	messageType: Generatedtest_Example_Person.self,
	insertSQL: PersonInsertSQL,
	upsertSQL: PersonUpsertSQL,
	decodeAnyJSON: { try decodeAnyJSON($0, as: Generatedtest_Example_Person.self) },
	decodeBinary: { try Generatedtest_Example_Person(serializedBytes: $0) },
	encodeAnyJSON: { message in
		guard let data = message as? Generatedtest_Example_Person else { throw ProprDBError("expected Generatedtest_Example_Person") }
		return try marshalAnyJSON(data, typeName: PersonTypeName)
	},
	messagesEqual: { left, right in
		guard let left = left as? Generatedtest_Example_Person, let right = right as? Generatedtest_Example_Person else { return false }
		return left == right
	},
	projectedValues: { message in
		guard let data = message as? Generatedtest_Example_Person else { throw ProprDBError("expected Generatedtest_Example_Person") }
		var values: [SQLiteBindValue] = []
		values.append(sqliteBindValue(data.name))
		values.append(sqliteBindValue(data.age))
		return values
	}
)

public struct PersonRow: Equatable, Sendable {
	public var id: String
	public var atNs: Int64
	public var data: Generatedtest_Example_Person
	public init(id: String, atNs: Int64, data: Generatedtest_Example_Person) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

public typealias PersonChange = TableChange<Generatedtest_Example_Person>

struct PersonTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = q
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try q.execute(PersonCreateTableSQL)
		let existingColumns = try q.withRows("PRAGMA table_info(\"\(PersonTableName)\")") { rows in
			var columns = Set<String>()
			while let row = try rows.next() {
				columns.insert(try row.string(at: 1))
			}
			return columns
		}
		if !existingColumns.contains("name") {
			try q.execute("ALTER TABLE " + PersonTableNameQuoted + " ADD COLUMN \"name\" TEXT NOT NULL DEFAULT ''")
		}
		if !existingColumns.contains("age") {
			try q.execute("ALTER TABLE " + PersonTableNameQuoted + " ADD COLUMN \"age\" INTEGER NOT NULL DEFAULT 0")
		}
		try ensureManagedIndexes(q, tableName: PersonTableName, generatedIndexPrefix: PersonGeneratedIndexPrefix, createIndexSQL: [
			PersonCreateIndexSQL1,
			PersonCreateIndexSQL2,
		], desiredIndexNames: [
			"idx_generatedtest_example_person__name",
			"idx_generatedtest_example_person__name_age",
		])
		let currentSchema = try q.withRows("SELECT schema_hash FROM \(_proprdbSchemaTableName) WHERE table_name = ?", arguments: [PersonTableName]) { rows -> String? in
			if let row = try rows.next() {
				return try row.string(at: 0)
			}
			return nil as String?
		}
		if let currentSchema, currentSchema != PersonProjectionSchema {
			try reproject()
			try q.execute("UPDATE \(_proprdbSchemaTableName) SET schema_hash = ? WHERE table_name = ?", arguments: [PersonProjectionSchema, PersonTableName])
		} else if currentSchema == nil {
			try q.execute("INSERT INTO \(_proprdbSchemaTableName) (table_name, schema_hash) VALUES (?, ?)", arguments: [PersonTableName, PersonProjectionSchema])
		}
		try drainUnknownRows(PersonTypeName)
	}

	func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) throws -> [PersonRow] {
		var query = "SELECT id, at_ns, data FROM " + PersonTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try q.withRows(query, bindValues: arguments) { rows in
			var result: [PersonRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Person(serializedBytes: dataBytes)
				result.append(PersonRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
	}

	func insert(_ data: Generatedtest_Example_Person) throws -> PersonRow {
		let id = try uuidV7()
		try validateUUID(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	func insertWithID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		try validateForWrite(data)
		let atNs = try writeLocalObject(q, binding: PersonGeneratedBinding, id: id, message: data, insert: true)
		return PersonRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		try validateForWrite(data)
		let atNs = try writeLocalObject(q, binding: PersonGeneratedBinding, id: id, message: data, insert: false)
		return PersonRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: PersonRow) throws -> PersonRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try deleteLocalObject(q, binding: PersonGeneratedBinding, id: id)
	}

	func deleteRow(_ row: PersonRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Person) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalAnyJSON(data, typeName: PersonTypeName)
		try applyIncomingObject(q, binding: PersonGeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalTypeOnlyAnyJSON(typeName: PersonTypeName)
		try applyIncomingObject(q, binding: PersonGeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))
	}

	private func reproject() throws {
		let rowsToReproject = try q.withRows("SELECT id, data FROM " + PersonTableNameQuoted) { rows in
			var buffered: [(String, Data)] = []
			while let row = try rows.next() {
				buffered.append((try row.string(at: 0), try row.data(at: 1)))
			}
			return buffered
		}
		for (id, dataBytes) in rowsToReproject {
			let data = try Generatedtest_Example_Person(serializedBytes: dataBytes)
			var reprojectArguments: [Any?] = []
			reprojectArguments.append(data.name)
			reprojectArguments.append(data.age)
			reprojectArguments.append(id)
			try q.execute(PersonReprojectSQL, arguments: reprojectArguments)
		}
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		guard typeName == PersonTypeName else { throw ProprDBError("unexpected type name \(typeName)") }
		try drainBoundUnknown(q, bindings: [PersonGeneratedBinding])
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(PersonTypeName)
	}

	func changes() -> AsyncStream<PersonChange> {
		tableChanges(q, tableName: PersonTableName, as: Generatedtest_Example_Person.self)
	}

}

let NoteTableName = "generatedtest_example_note"
private let NoteTableNameQuoted = quoteSQLiteIdentifier(NoteTableName)
let NoteTypeName = "generatedtest.example.Note"
let NoteProjectionSchema = "text:string"
private let NoteCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_note\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"text\" TEXT NOT NULL DEFAULT '')"
private let NoteInsertSQL = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?)"
private let NoteUpsertSQL = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"text\" = excluded.\"text\""
private let NoteGeneratedIndexPrefix = "idx_generatedtest_example_note__"
private let NoteReprojectSQL = "UPDATE \"generatedtest_example_note\" SET \"text\" = ? WHERE id = ?"

private let NoteGeneratedBinding = GeneratedTableBinding(
	descriptor: GeneratedTableDescriptor(tableName: NoteTableName, typeName: NoteTypeName, isCore: false, syncEnabled: false, changeListenersEnabled: false),
	messageType: Generatedtest_Example_Note.self,
	insertSQL: NoteInsertSQL,
	upsertSQL: NoteUpsertSQL,
	decodeAnyJSON: { try decodeAnyJSON($0, as: Generatedtest_Example_Note.self) },
	decodeBinary: { try Generatedtest_Example_Note(serializedBytes: $0) },
	encodeAnyJSON: { message in
		guard let data = message as? Generatedtest_Example_Note else { throw ProprDBError("expected Generatedtest_Example_Note") }
		return try marshalAnyJSON(data, typeName: NoteTypeName)
	},
	messagesEqual: { left, right in
		guard let left = left as? Generatedtest_Example_Note, let right = right as? Generatedtest_Example_Note else { return false }
		return left == right
	},
	projectedValues: { message in
		guard let data = message as? Generatedtest_Example_Note else { throw ProprDBError("expected Generatedtest_Example_Note") }
		var values: [SQLiteBindValue] = []
		values.append(sqliteBindValue(data.text))
		return values
	}
)

public struct NoteRow: Equatable, Sendable {
	public var id: String
	public var atNs: Int64
	public var data: Generatedtest_Example_Note
	public init(id: String, atNs: Int64, data: Generatedtest_Example_Note) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

struct NoteTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = q
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try q.execute(NoteCreateTableSQL)
		let existingColumns = try q.withRows("PRAGMA table_info(\"\(NoteTableName)\")") { rows in
			var columns = Set<String>()
			while let row = try rows.next() {
				columns.insert(try row.string(at: 1))
			}
			return columns
		}
		if !existingColumns.contains("text") {
			try q.execute("ALTER TABLE " + NoteTableNameQuoted + " ADD COLUMN \"text\" TEXT NOT NULL DEFAULT ''")
		}
		try ensureManagedIndexes(q, tableName: NoteTableName, generatedIndexPrefix: NoteGeneratedIndexPrefix, createIndexSQL: [
		], desiredIndexNames: [
		])
		let currentSchema = try q.withRows("SELECT schema_hash FROM \(_proprdbSchemaTableName) WHERE table_name = ?", arguments: [NoteTableName]) { rows -> String? in
			if let row = try rows.next() {
				return try row.string(at: 0)
			}
			return nil as String?
		}
		if let currentSchema, currentSchema != NoteProjectionSchema {
			try reproject()
			try q.execute("UPDATE \(_proprdbSchemaTableName) SET schema_hash = ? WHERE table_name = ?", arguments: [NoteProjectionSchema, NoteTableName])
		} else if currentSchema == nil {
			try q.execute("INSERT INTO \(_proprdbSchemaTableName) (table_name, schema_hash) VALUES (?, ?)", arguments: [NoteTableName, NoteProjectionSchema])
		}
		try drainUnknownRows(NoteTypeName)
	}

	func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) throws -> [NoteRow] {
		var query = "SELECT id, at_ns, data FROM " + NoteTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try q.withRows(query, bindValues: arguments) { rows in
			var result: [NoteRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Note(serializedBytes: dataBytes)
				result.append(NoteRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
	}

	func insert(_ data: Generatedtest_Example_Note) throws -> NoteRow {
		let id = try uuidV7()
		try validateUUID(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		let atNs = try writeLocalObject(q, binding: NoteGeneratedBinding, id: id, message: data, insert: true)
		return NoteRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		let atNs = try writeLocalObject(q, binding: NoteGeneratedBinding, id: id, message: data, insert: false)
		return NoteRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: NoteRow) throws -> NoteRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try deleteLocalObject(q, binding: NoteGeneratedBinding, id: id)
	}

	func deleteRow(_ row: NoteRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Note) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalAnyJSON(data, typeName: NoteTypeName)
		try applyIncomingObject(q, binding: NoteGeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalTypeOnlyAnyJSON(typeName: NoteTypeName)
		try applyIncomingObject(q, binding: NoteGeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))
	}

	private func reproject() throws {
		let rowsToReproject = try q.withRows("SELECT id, data FROM " + NoteTableNameQuoted) { rows in
			var buffered: [(String, Data)] = []
			while let row = try rows.next() {
				buffered.append((try row.string(at: 0), try row.data(at: 1)))
			}
			return buffered
		}
		for (id, dataBytes) in rowsToReproject {
			let data = try Generatedtest_Example_Note(serializedBytes: dataBytes)
			var reprojectArguments: [Any?] = []
			reprojectArguments.append(data.text)
			reprojectArguments.append(id)
			try q.execute(NoteReprojectSQL, arguments: reprojectArguments)
		}
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		guard typeName == NoteTypeName else { throw ProprDBError("unexpected type name \(typeName)") }
		try drainBoundUnknown(q, bindings: [NoteGeneratedBinding])
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(NoteTypeName)
	}

}

private let crudGeneratedBindings = [
	PersonGeneratedBinding,
	NoteGeneratedBinding,
]

struct CRUD {
	let person: PersonTable
	let note: NoteTable
	init(_ q: any DBTX) {
		let tracked = withChangeListeners(q)
		self.person = PersonTable(tracked)
		self.note = NoteTable(tracked)
	}
	private func dbtx() -> any DBTX { person.q }
	func tableDescriptors() -> [GeneratedTableDescriptor] { crudGeneratedBindings.map(\.descriptor) + coreTableDescriptors() }
	func initialize() throws {
		try person.initialize()
		try note.initialize()
	}
	func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try prepareBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote) }
	func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try acknowledgeBoundJSONL(dbtx(), checkpoint: checkpoint) }
	func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try discardBoundJSONL(dbtx(), checkpoint: checkpoint) }
	func writeJSONL(remote: String) throws -> String {
		let prepared = try prepareJSONL(remote: remote)
		try acknowledgeJSONL(prepared.checkpoint)
		return prepared.text
	}
	func readJSONL(remote: String, text: String) throws { try readBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote, text: text) }
}

public struct PersonTableProxy: Sendable {
	fileprivate let actor: ProprDBActor

	public func initialize() async throws { try await actor._personInitialize() }
	public func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) async throws -> [PersonRow] { try await actor._personSelect(where: whereClause, arguments: arguments) }
	public func insert(_ data: Generatedtest_Example_Person) async throws -> PersonRow { try await actor._personInsert(data) }
	public func insertWithID(_ id: String, data: Generatedtest_Example_Person) async throws -> PersonRow { try await actor._personInsertWithID(id, data: data) }
	public func updateByID(_ id: String, data: Generatedtest_Example_Person) async throws -> PersonRow { try await actor._personUpdateByID(id, data: data) }
	public func updateRow(_ row: PersonRow) async throws -> PersonRow { try await actor._personUpdateRow(row) }
	public func deleteByID(_ id: String) async throws { try await actor._personDeleteByID(id) }
	public func deleteRow(_ row: PersonRow) async throws { try await actor._personDeleteRow(row) }
	public func drainUnknownRows() async throws { try await actor._personDrainUnknownRows() }
	public func changes() async throws -> AsyncStream<PersonChange> { try await actor._personChanges() }
}

public struct NoteTableProxy: Sendable {
	fileprivate let actor: ProprDBActor

	public func initialize() async throws { try await actor._noteInitialize() }
	public func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) async throws -> [NoteRow] { try await actor._noteSelect(where: whereClause, arguments: arguments) }
	public func insert(_ data: Generatedtest_Example_Note) async throws -> NoteRow { try await actor._noteInsert(data) }
	public func updateByID(_ id: String, data: Generatedtest_Example_Note) async throws -> NoteRow { try await actor._noteUpdateByID(id, data: data) }
	public func updateRow(_ row: NoteRow) async throws -> NoteRow { try await actor._noteUpdateRow(row) }
	public func deleteByID(_ id: String) async throws { try await actor._noteDeleteByID(id) }
	public func deleteRow(_ row: NoteRow) async throws { try await actor._noteDeleteRow(row) }
	public func drainUnknownRows() async throws { try await actor._noteDrainUnknownRows() }
}

extension ProprDBActor {
	public func initialize() throws { try withDatabase { try CRUD($0).initialize() } }
	public func tableDescriptors() throws -> [GeneratedTableDescriptor] { try withDatabase { CRUD($0).tableDescriptors() } }
	public nonisolated var person: PersonTableProxy { PersonTableProxy(actor: self) }
	fileprivate func _personInitialize() throws { try withDatabase { try CRUD($0).person.initialize() } }
	fileprivate func _personSelect(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [PersonRow] { try withDatabase { try CRUD($0).person.select(where: whereClause, arguments: arguments) } }
	fileprivate func _personInsert(_ data: Generatedtest_Example_Person) throws -> PersonRow { try withDatabase { try CRUD($0).person.insert(data) } }
	fileprivate func _personInsertWithID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow { try withDatabase { try CRUD($0).person.insertWithID(id, data: data) } }
	fileprivate func _personUpdateByID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow { try withDatabase { try CRUD($0).person.updateByID(id, data: data) } }
	fileprivate func _personUpdateRow(_ row: PersonRow) throws -> PersonRow { try withDatabase { try CRUD($0).person.updateRow(row) } }
	fileprivate func _personDeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).person.deleteByID(id) } }
	fileprivate func _personDeleteRow(_ row: PersonRow) throws { try withDatabase { try CRUD($0).person.deleteRow(row) } }
	fileprivate func _personDrainUnknownRows() throws { try withDatabase { try CRUD($0).person.drainUnknownRows() } }
	fileprivate func _personChanges() throws -> AsyncStream<PersonChange> { try withDatabase { CRUD($0).person.changes() } }
	public nonisolated var note: NoteTableProxy { NoteTableProxy(actor: self) }
	fileprivate func _noteInitialize() throws { try withDatabase { try CRUD($0).note.initialize() } }
	fileprivate func _noteSelect(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [NoteRow] { try withDatabase { try CRUD($0).note.select(where: whereClause, arguments: arguments) } }
	fileprivate func _noteInsert(_ data: Generatedtest_Example_Note) throws -> NoteRow { try withDatabase { try CRUD($0).note.insert(data) } }
	fileprivate func _noteUpdateByID(_ id: String, data: Generatedtest_Example_Note) throws -> NoteRow { try withDatabase { try CRUD($0).note.updateByID(id, data: data) } }
	fileprivate func _noteUpdateRow(_ row: NoteRow) throws -> NoteRow { try withDatabase { try CRUD($0).note.updateRow(row) } }
	fileprivate func _noteDeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).note.deleteByID(id) } }
	fileprivate func _noteDeleteRow(_ row: NoteRow) throws { try withDatabase { try CRUD($0).note.deleteRow(row) } }
	fileprivate func _noteDrainUnknownRows() throws { try withDatabase { try CRUD($0).note.drainUnknownRows() } }
	public func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try withDatabase { try CRUD($0).prepareJSONL(remote: remote) } }
	public func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).acknowledgeJSONL(checkpoint) } }
	public func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).discardJSONL(checkpoint) } }
	public func writeJSONL(remote: String) throws -> String { try withDatabase { try CRUD($0).writeJSONL(remote: remote) } }
	public func readJSONL(remote: String, text: String) throws { try withDatabase { try CRUD($0).readJSONL(remote: remote, text: text) } }
}
