// Code generated by protoc-gen-proprdb-swift. DO NOT EDIT.

import Foundation
import SwiftProtobuf
import ProprDBSwiftRuntime

let PersonTableName = "generatedtest_example_person"
private let PersonTableNameQuoted = quoteSQLiteIdentifier(PersonTableName)
let PersonTypeName = "generatedtest.example.Person"
let PersonProjectionSchema = "name:string;age:int64"
private let PersonCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_person\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"name\" TEXT NOT NULL DEFAULT '', \"age\" INTEGER NOT NULL DEFAULT 0)"
private let PersonInsertSQL = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?)"
private let PersonUpsertSQL = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"name\" = excluded.\"name\", \"age\" = excluded.\"age\""
private let PersonGeneratedIndexPrefix = "idx_generatedtest_example_person__"
private let PersonCreateIndexSQL1 = "CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name\" ON \"generatedtest_example_person\" (\"name\")"
private let PersonCreateIndexSQL2 = "CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name_age\" ON \"generatedtest_example_person\" (\"name\", \"age\")"

private let PersonGeneratedBinding = GeneratedTableBinding(
	descriptor: GeneratedTableDescriptor(tableName: PersonTableName, typeName: PersonTypeName, isCore: false, syncEnabled: true, changeListenersEnabled: true, queryStatisticsEnabled: true),
	messageType: Generatedtest_Example_Person.self,
	insertSQL: PersonInsertSQL,
	upsertSQL: PersonUpsertSQL,
	createTableSQL: PersonCreateTableSQL,
	projectionSchema: PersonProjectionSchema,
	projectedColumns: [
		ProjectedColumnDescriptor(name: "name", protoKind: "string", sqliteType: "TEXT", defaultSQL: "''", nullable: false, legacyOneofPresenceRepair: false),
		ProjectedColumnDescriptor(name: "age", protoKind: "int64", sqliteType: "INTEGER", defaultSQL: "0", nullable: false, legacyOneofPresenceRepair: false),
	],
	generatedIndexes: [
		GeneratedIndexDescriptor(name: "idx_generatedtest_example_person__name", createSQL: PersonCreateIndexSQL1),
		GeneratedIndexDescriptor(name: "idx_generatedtest_example_person__name_age", createSQL: PersonCreateIndexSQL2),
	],
	generatedIndexPrefix: PersonGeneratedIndexPrefix,
	decodeAnyJSON: { try decodeAnyJSON($0, as: Generatedtest_Example_Person.self) },
	decodeBinary: { try Generatedtest_Example_Person(serializedBytes: $0) },
	encodeAnyJSON: { message in
		guard let data = message as? Generatedtest_Example_Person else { throw ProprDBError("expected Generatedtest_Example_Person") }
		return try marshalAnyJSON(data, typeName: PersonTypeName)
	},
	messagesEqual: { left, right in
		guard let left = left as? Generatedtest_Example_Person, let right = right as? Generatedtest_Example_Person else { return false }
		return left == right
	},
	projectedValues: { message in
		guard let data = message as? Generatedtest_Example_Person else { throw ProprDBError("expected Generatedtest_Example_Person") }
		var values: [SQLiteBindValue] = []
		values.append(sqliteBindValue(data.name))
		values.append(sqliteBindValue(data.age))
		return values
	}
)

public struct PersonRow: Equatable, Sendable {
	public var id: String
	public var atNs: Int64
	public var data: Generatedtest_Example_Person
	public init(id: String, atNs: Int64, data: Generatedtest_Example_Person) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

public typealias PersonChange = TableChange<Generatedtest_Example_Person>

struct PersonTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = withChangeListeners(q)
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try auditObjectIDs(q, bindings: [PersonGeneratedBinding])
		try reconcileGeneratedTable(q, binding: PersonGeneratedBinding)
		try drainUnknownRows(PersonTypeName)
	}

	func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) throws -> [PersonRow] {
		var query = "SELECT id, at_ns, data FROM " + PersonTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try measureQuery(q, tableName: PersonTableName, query: query) {
		return try q.withRows(query, bindValues: arguments) { rows in
			var result: [PersonRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Person(serializedBytes: dataBytes)
				result.append(PersonRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
		}
	}

	func insert(_ data: Generatedtest_Example_Person) throws -> PersonRow {
		let id = try uuidV7()
		try validateUUIDV7(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	func insertWithID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUIDV7(id)
		try validateForWrite(data)
		let atNs = try writeLocalObject(q, binding: PersonGeneratedBinding, id: id, message: data, insert: true)
		return PersonRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUIDV7(id)
		try validateForWrite(data)
		let atNs = try writeLocalObject(q, binding: PersonGeneratedBinding, id: id, message: data, insert: false)
		return PersonRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: PersonRow) throws -> PersonRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try deleteLocalObject(q, binding: PersonGeneratedBinding, id: id)
	}

	func deleteRow(_ row: PersonRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Person) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalAnyJSON(data, typeName: PersonTypeName)
		try applyIncomingObject(q, binding: PersonGeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalTypeOnlyAnyJSON(typeName: PersonTypeName)
		try applyIncomingObject(q, binding: PersonGeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		guard typeName == PersonTypeName else { throw ProprDBError("unexpected type name \(typeName)") }
		try drainBoundUnknown(q, bindings: [PersonGeneratedBinding])
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(PersonTypeName)
	}

	func changes() -> AsyncStream<PersonChange> {
		tableChanges(q, tableName: PersonTableName, as: Generatedtest_Example_Person.self)
	}

}

let NoteTableName = "generatedtest_example_note"
private let NoteTableNameQuoted = quoteSQLiteIdentifier(NoteTableName)
let NoteTypeName = "generatedtest.example.Note"
let NoteProjectionSchema = "text:string"
private let NoteCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_note\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"text\" TEXT NOT NULL DEFAULT '')"
private let NoteInsertSQL = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?)"
private let NoteUpsertSQL = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"text\" = excluded.\"text\""
private let NoteGeneratedIndexPrefix = "idx_generatedtest_example_note__"

private let NoteGeneratedBinding = GeneratedTableBinding(
	descriptor: GeneratedTableDescriptor(tableName: NoteTableName, typeName: NoteTypeName, isCore: false, syncEnabled: false, changeListenersEnabled: true, queryStatisticsEnabled: false),
	messageType: Generatedtest_Example_Note.self,
	insertSQL: NoteInsertSQL,
	upsertSQL: NoteUpsertSQL,
	createTableSQL: NoteCreateTableSQL,
	projectionSchema: NoteProjectionSchema,
	projectedColumns: [
		ProjectedColumnDescriptor(name: "text", protoKind: "string", sqliteType: "TEXT", defaultSQL: "''", nullable: false, legacyOneofPresenceRepair: false),
	],
	generatedIndexes: [
	],
	generatedIndexPrefix: NoteGeneratedIndexPrefix,
	decodeAnyJSON: { try decodeAnyJSON($0, as: Generatedtest_Example_Note.self) },
	decodeBinary: { try Generatedtest_Example_Note(serializedBytes: $0) },
	encodeAnyJSON: { message in
		guard let data = message as? Generatedtest_Example_Note else { throw ProprDBError("expected Generatedtest_Example_Note") }
		return try marshalAnyJSON(data, typeName: NoteTypeName)
	},
	messagesEqual: { left, right in
		guard let left = left as? Generatedtest_Example_Note, let right = right as? Generatedtest_Example_Note else { return false }
		return left == right
	},
	projectedValues: { message in
		guard let data = message as? Generatedtest_Example_Note else { throw ProprDBError("expected Generatedtest_Example_Note") }
		var values: [SQLiteBindValue] = []
		values.append(sqliteBindValue(data.text))
		return values
	}
)

public struct NoteRow: Equatable, Sendable {
	public var id: String
	public var atNs: Int64
	public var data: Generatedtest_Example_Note
	public init(id: String, atNs: Int64, data: Generatedtest_Example_Note) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

public typealias NoteChange = TableChange<Generatedtest_Example_Note>

struct NoteTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = withChangeListeners(q)
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try auditObjectIDs(q, bindings: [NoteGeneratedBinding])
		try reconcileGeneratedTable(q, binding: NoteGeneratedBinding)
		try drainUnknownRows(NoteTypeName)
	}

	func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) throws -> [NoteRow] {
		var query = "SELECT id, at_ns, data FROM " + NoteTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try q.withRows(query, bindValues: arguments) { rows in
			var result: [NoteRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Note(serializedBytes: dataBytes)
				result.append(NoteRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
	}

	func insert(_ data: Generatedtest_Example_Note) throws -> NoteRow {
		let id = try uuidV7()
		try validateUUIDV7(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUIDV7(id)
		let atNs = try writeLocalObject(q, binding: NoteGeneratedBinding, id: id, message: data, insert: true)
		return NoteRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUIDV7(id)
		let atNs = try writeLocalObject(q, binding: NoteGeneratedBinding, id: id, message: data, insert: false)
		return NoteRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: NoteRow) throws -> NoteRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try deleteLocalObject(q, binding: NoteGeneratedBinding, id: id)
	}

	func deleteRow(_ row: NoteRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Note) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalAnyJSON(data, typeName: NoteTypeName)
		try applyIncomingObject(q, binding: NoteGeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalTypeOnlyAnyJSON(typeName: NoteTypeName)
		try applyIncomingObject(q, binding: NoteGeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		guard typeName == NoteTypeName else { throw ProprDBError("unexpected type name \(typeName)") }
		try drainBoundUnknown(q, bindings: [NoteGeneratedBinding])
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(NoteTypeName)
	}

	func changes() -> AsyncStream<NoteChange> {
		tableChanges(q, tableName: NoteTableName, as: Generatedtest_Example_Note.self)
	}

}

let ChoiceTableName = "generatedtest_example_choice"
private let ChoiceTableNameQuoted = quoteSQLiteIdentifier(ChoiceTableName)
let ChoiceTypeName = "generatedtest.example.Choice"
let ChoiceProjectionSchema = "label:string:optional"
private let ChoiceCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_choice\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"label\" TEXT)"
private let ChoiceInsertSQL = "INSERT INTO \"generatedtest_example_choice\" (\"id\", \"at_ns\", \"data\", \"label\") VALUES (?, ?, ?, ?)"
private let ChoiceUpsertSQL = "INSERT INTO \"generatedtest_example_choice\" (\"id\", \"at_ns\", \"data\", \"label\") VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"label\" = excluded.\"label\""
private let ChoiceGeneratedIndexPrefix = "idx_generatedtest_example_choice__"

private let ChoiceGeneratedBinding = GeneratedTableBinding(
	descriptor: GeneratedTableDescriptor(tableName: ChoiceTableName, typeName: ChoiceTypeName, isCore: false, syncEnabled: true, changeListenersEnabled: false, queryStatisticsEnabled: false),
	messageType: Generatedtest_Example_Choice.self,
	insertSQL: ChoiceInsertSQL,
	upsertSQL: ChoiceUpsertSQL,
	createTableSQL: ChoiceCreateTableSQL,
	projectionSchema: ChoiceProjectionSchema,
	projectedColumns: [
		ProjectedColumnDescriptor(name: "label", protoKind: "string", sqliteType: "TEXT", defaultSQL: "''", nullable: true, legacyOneofPresenceRepair: true),
	],
	generatedIndexes: [
	],
	generatedIndexPrefix: ChoiceGeneratedIndexPrefix,
	decodeAnyJSON: { try decodeAnyJSON($0, as: Generatedtest_Example_Choice.self) },
	decodeBinary: { try Generatedtest_Example_Choice(serializedBytes: $0) },
	encodeAnyJSON: { message in
		guard let data = message as? Generatedtest_Example_Choice else { throw ProprDBError("expected Generatedtest_Example_Choice") }
		return try marshalAnyJSON(data, typeName: ChoiceTypeName)
	},
	messagesEqual: { left, right in
		guard let left = left as? Generatedtest_Example_Choice, let right = right as? Generatedtest_Example_Choice else { return false }
		return left == right
	},
	projectedValues: { message in
		guard let data = message as? Generatedtest_Example_Choice else { throw ProprDBError("expected Generatedtest_Example_Choice") }
		var values: [SQLiteBindValue] = []
		if case .label = data.selection { values.append(sqliteBindValue(data.label)) } else { values.append(.null) }
		return values
	}
)

public struct ChoiceRow: Equatable, Sendable {
	public var id: String
	public var atNs: Int64
	public var data: Generatedtest_Example_Choice
	public init(id: String, atNs: Int64, data: Generatedtest_Example_Choice) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

struct ChoiceTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = q
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try auditObjectIDs(q, bindings: [ChoiceGeneratedBinding])
		try reconcileGeneratedTable(q, binding: ChoiceGeneratedBinding)
		try drainUnknownRows(ChoiceTypeName)
	}

	func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) throws -> [ChoiceRow] {
		var query = "SELECT id, at_ns, data FROM " + ChoiceTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try q.withRows(query, bindValues: arguments) { rows in
			var result: [ChoiceRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Choice(serializedBytes: dataBytes)
				result.append(ChoiceRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
	}

	func insert(_ data: Generatedtest_Example_Choice) throws -> ChoiceRow {
		let id = try uuidV7()
		try validateUUIDV7(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Choice) throws -> ChoiceRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUIDV7(id)
		let atNs = try writeLocalObject(q, binding: ChoiceGeneratedBinding, id: id, message: data, insert: true)
		return ChoiceRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Choice) throws -> ChoiceRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUIDV7(id)
		let atNs = try writeLocalObject(q, binding: ChoiceGeneratedBinding, id: id, message: data, insert: false)
		return ChoiceRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: ChoiceRow) throws -> ChoiceRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try deleteLocalObject(q, binding: ChoiceGeneratedBinding, id: id)
	}

	func deleteRow(_ row: ChoiceRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Choice) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalAnyJSON(data, typeName: ChoiceTypeName)
		try applyIncomingObject(q, binding: ChoiceGeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataJSON = try marshalTypeOnlyAnyJSON(typeName: ChoiceTypeName)
		try applyIncomingObject(q, binding: ChoiceGeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		guard typeName == ChoiceTypeName else { throw ProprDBError("unexpected type name \(typeName)") }
		try drainBoundUnknown(q, bindings: [ChoiceGeneratedBinding])
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(ChoiceTypeName)
	}

}

private let crudGeneratedBindings = [
	PersonGeneratedBinding,
	NoteGeneratedBinding,
	ChoiceGeneratedBinding,
]

struct CRUD {
	let person: PersonTable
	let note: NoteTable
	let choice: ChoiceTable
	init(_ q: any DBTX) {
		let tracked = withChangeListeners(q)
		self.person = PersonTable(tracked)
		self.note = NoteTable(tracked)
		self.choice = ChoiceTable(tracked)
	}
	private func dbtx() -> any DBTX { person.q }
	func tableDescriptors() -> [GeneratedTableDescriptor] { crudGeneratedBindings.map(\.descriptor) + coreTableDescriptors() }
	func initialize() throws {
		try person.initialize()
		try note.initialize()
		try choice.initialize()
	}
	func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try prepareBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote) }
	func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try acknowledgeBoundJSONL(dbtx(), checkpoint: checkpoint) }
	func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try discardBoundJSONL(dbtx(), checkpoint: checkpoint) }
	func writeJSONL(remote: String) throws -> String {
		let prepared = try prepareJSONL(remote: remote)
		try acknowledgeJSONL(prepared.checkpoint)
		return prepared.text
	}
	func readJSONL(remote: String, text: String) throws { try readBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote, text: text) }
}

public struct PersonTableProxy: Sendable {
	fileprivate let actor: ProprDBActor

	public func initialize() async throws { try await actor._personInitialize() }
	public func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) async throws -> [PersonRow] { try await actor._personSelect(where: whereClause, arguments: arguments) }
	public func insert(_ data: Generatedtest_Example_Person) async throws -> PersonRow { try await actor._personInsert(data) }
	public func insertWithID(_ id: String, data: Generatedtest_Example_Person) async throws -> PersonRow { try await actor._personInsertWithID(id, data: data) }
	public func updateByID(_ id: String, data: Generatedtest_Example_Person) async throws -> PersonRow { try await actor._personUpdateByID(id, data: data) }
	public func updateRow(_ row: PersonRow) async throws -> PersonRow { try await actor._personUpdateRow(row) }
	public func deleteByID(_ id: String) async throws { try await actor._personDeleteByID(id) }
	public func deleteRow(_ row: PersonRow) async throws { try await actor._personDeleteRow(row) }
	public func drainUnknownRows() async throws { try await actor._personDrainUnknownRows() }
	public func changes() async throws -> AsyncStream<PersonChange> { try await actor._personChanges() }
}

public struct NoteTableProxy: Sendable {
	fileprivate let actor: ProprDBActor

	public func initialize() async throws { try await actor._noteInitialize() }
	public func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) async throws -> [NoteRow] { try await actor._noteSelect(where: whereClause, arguments: arguments) }
	public func insert(_ data: Generatedtest_Example_Note) async throws -> NoteRow { try await actor._noteInsert(data) }
	public func updateByID(_ id: String, data: Generatedtest_Example_Note) async throws -> NoteRow { try await actor._noteUpdateByID(id, data: data) }
	public func updateRow(_ row: NoteRow) async throws -> NoteRow { try await actor._noteUpdateRow(row) }
	public func deleteByID(_ id: String) async throws { try await actor._noteDeleteByID(id) }
	public func deleteRow(_ row: NoteRow) async throws { try await actor._noteDeleteRow(row) }
	public func drainUnknownRows() async throws { try await actor._noteDrainUnknownRows() }
	public func changes() async throws -> AsyncStream<NoteChange> { try await actor._noteChanges() }
}

public struct ChoiceTableProxy: Sendable {
	fileprivate let actor: ProprDBActor

	public func initialize() async throws { try await actor._choiceInitialize() }
	public func select(where whereClause: String = "", arguments: [SQLiteBindValue] = []) async throws -> [ChoiceRow] { try await actor._choiceSelect(where: whereClause, arguments: arguments) }
	public func insert(_ data: Generatedtest_Example_Choice) async throws -> ChoiceRow { try await actor._choiceInsert(data) }
	public func updateByID(_ id: String, data: Generatedtest_Example_Choice) async throws -> ChoiceRow { try await actor._choiceUpdateByID(id, data: data) }
	public func updateRow(_ row: ChoiceRow) async throws -> ChoiceRow { try await actor._choiceUpdateRow(row) }
	public func deleteByID(_ id: String) async throws { try await actor._choiceDeleteByID(id) }
	public func deleteRow(_ row: ChoiceRow) async throws { try await actor._choiceDeleteRow(row) }
	public func drainUnknownRows() async throws { try await actor._choiceDrainUnknownRows() }
}

extension ProprDBActor {
	public func initialize() throws { try withDatabase { try CRUD($0).initialize() } }
	public func tableDescriptors() throws -> [GeneratedTableDescriptor] { try withDatabase { CRUD($0).tableDescriptors() } }
	public nonisolated var person: PersonTableProxy { PersonTableProxy(actor: self) }
	fileprivate func _personInitialize() throws { try withDatabase { try CRUD($0).person.initialize() } }
	fileprivate func _personSelect(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [PersonRow] { try withDatabase { try CRUD($0).person.select(where: whereClause, arguments: arguments) } }
	fileprivate func _personInsert(_ data: Generatedtest_Example_Person) throws -> PersonRow { try withDatabase { try CRUD($0).person.insert(data) } }
	fileprivate func _personInsertWithID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow { try withDatabase { try CRUD($0).person.insertWithID(id, data: data) } }
	fileprivate func _personUpdateByID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow { try withDatabase { try CRUD($0).person.updateByID(id, data: data) } }
	fileprivate func _personUpdateRow(_ row: PersonRow) throws -> PersonRow { try withDatabase { try CRUD($0).person.updateRow(row) } }
	fileprivate func _personDeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).person.deleteByID(id) } }
	fileprivate func _personDeleteRow(_ row: PersonRow) throws { try withDatabase { try CRUD($0).person.deleteRow(row) } }
	fileprivate func _personDrainUnknownRows() throws { try withDatabase { try CRUD($0).person.drainUnknownRows() } }
	fileprivate func _personChanges() throws -> AsyncStream<PersonChange> { try withDatabase { CRUD($0).person.changes() } }
	public nonisolated var note: NoteTableProxy { NoteTableProxy(actor: self) }
	fileprivate func _noteInitialize() throws { try withDatabase { try CRUD($0).note.initialize() } }
	fileprivate func _noteSelect(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [NoteRow] { try withDatabase { try CRUD($0).note.select(where: whereClause, arguments: arguments) } }
	fileprivate func _noteInsert(_ data: Generatedtest_Example_Note) throws -> NoteRow { try withDatabase { try CRUD($0).note.insert(data) } }
	fileprivate func _noteUpdateByID(_ id: String, data: Generatedtest_Example_Note) throws -> NoteRow { try withDatabase { try CRUD($0).note.updateByID(id, data: data) } }
	fileprivate func _noteUpdateRow(_ row: NoteRow) throws -> NoteRow { try withDatabase { try CRUD($0).note.updateRow(row) } }
	fileprivate func _noteDeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).note.deleteByID(id) } }
	fileprivate func _noteDeleteRow(_ row: NoteRow) throws { try withDatabase { try CRUD($0).note.deleteRow(row) } }
	fileprivate func _noteDrainUnknownRows() throws { try withDatabase { try CRUD($0).note.drainUnknownRows() } }
	fileprivate func _noteChanges() throws -> AsyncStream<NoteChange> { try withDatabase { CRUD($0).note.changes() } }
	public nonisolated var choice: ChoiceTableProxy { ChoiceTableProxy(actor: self) }
	fileprivate func _choiceInitialize() throws { try withDatabase { try CRUD($0).choice.initialize() } }
	fileprivate func _choiceSelect(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [ChoiceRow] { try withDatabase { try CRUD($0).choice.select(where: whereClause, arguments: arguments) } }
	fileprivate func _choiceInsert(_ data: Generatedtest_Example_Choice) throws -> ChoiceRow { try withDatabase { try CRUD($0).choice.insert(data) } }
	fileprivate func _choiceUpdateByID(_ id: String, data: Generatedtest_Example_Choice) throws -> ChoiceRow { try withDatabase { try CRUD($0).choice.updateByID(id, data: data) } }
	fileprivate func _choiceUpdateRow(_ row: ChoiceRow) throws -> ChoiceRow { try withDatabase { try CRUD($0).choice.updateRow(row) } }
	fileprivate func _choiceDeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).choice.deleteByID(id) } }
	fileprivate func _choiceDeleteRow(_ row: ChoiceRow) throws { try withDatabase { try CRUD($0).choice.deleteRow(row) } }
	fileprivate func _choiceDrainUnknownRows() throws { try withDatabase { try CRUD($0).choice.drainUnknownRows() } }
	public func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try withDatabase { try CRUD($0).prepareJSONL(remote: remote) } }
	public func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).acknowledgeJSONL(checkpoint) } }
	public func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).discardJSONL(checkpoint) } }
	public func writeJSONL(remote: String) throws -> String { try withDatabase { try CRUD($0).writeJSONL(remote: remote) } }
	public func readJSONL(remote: String, text: String) throws { try withDatabase { try CRUD($0).readJSONL(remote: remote, text: text) } }
}
