// Code generated by protoc-gen-proprdb-swift. DO NOT EDIT.

import Foundation
import SwiftProtobuf
import ProprDBSwiftRuntime

let PersonTableName = "generatedtest_example_person"
private let PersonTableNameQuoted = quoteSQLiteIdentifier(PersonTableName)
let PersonTypeName = "generatedtest.example.Person"
let PersonProjectionSchema = "name:string;age:int64"
private let PersonCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_person\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"name\" TEXT NOT NULL DEFAULT '', \"age\" INTEGER NOT NULL DEFAULT 0)"
private let PersonInsertSQL = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?)"
private let PersonUpsertSQL = "INSERT INTO \"generatedtest_example_person\" (\"id\", \"at_ns\", \"data\", \"name\", \"age\") VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"name\" = excluded.\"name\", \"age\" = excluded.\"age\""
private let PersonGeneratedIndexPrefix = "idx_generatedtest_example_person__"
private let PersonCreateIndexSQL1 = "CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name\" ON \"generatedtest_example_person\" (\"name\")"
private let PersonCreateIndexSQL2 = "CREATE INDEX IF NOT EXISTS \"idx_generatedtest_example_person__name_age\" ON \"generatedtest_example_person\" (\"name\", \"age\")"
private let PersonReprojectSQL = "UPDATE \"generatedtest_example_person\" SET \"name\" = ?, \"age\" = ? WHERE id = ?"

struct PersonRow: Equatable, Sendable {
	var id: String
	var atNs: Int64
	var data: Generatedtest_Example_Person
	init(id: String, atNs: Int64, data: Generatedtest_Example_Person) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

struct PersonTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = q
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try q.execute(PersonCreateTableSQL)
		let existingColumns = try q.withRows("PRAGMA table_info(\"\(PersonTableName)\")") { rows in
			var columns = Set<String>()
			while let row = try rows.next() {
				columns.insert(try row.string(at: 1))
			}
			return columns
		}
		if !existingColumns.contains("name") {
			try q.execute("ALTER TABLE " + PersonTableNameQuoted + " ADD COLUMN \"name\" TEXT NOT NULL DEFAULT ''")
		}
		if !existingColumns.contains("age") {
			try q.execute("ALTER TABLE " + PersonTableNameQuoted + " ADD COLUMN \"age\" INTEGER NOT NULL DEFAULT 0")
		}
		try ensureManagedIndexes(q, tableName: PersonTableName, generatedIndexPrefix: PersonGeneratedIndexPrefix, createIndexSQL: [
			PersonCreateIndexSQL1,
			PersonCreateIndexSQL2,
		], desiredIndexNames: [
			"idx_generatedtest_example_person__name",
			"idx_generatedtest_example_person__name_age",
		])
		let currentSchema = try q.withRows("SELECT schema_hash FROM \(_proprdbSchemaTableName) WHERE table_name = ?", arguments: [PersonTableName]) { rows -> String? in
			if let row = try rows.next() {
				return try row.string(at: 0)
			}
			return nil as String?
		}
		if let currentSchema, currentSchema != PersonProjectionSchema {
			try reproject()
			try q.execute("UPDATE \(_proprdbSchemaTableName) SET schema_hash = ? WHERE table_name = ?", arguments: [PersonProjectionSchema, PersonTableName])
		} else if currentSchema == nil {
			try q.execute("INSERT INTO \(_proprdbSchemaTableName) (table_name, schema_hash) VALUES (?, ?)", arguments: [PersonTableName, PersonProjectionSchema])
		}
		try drainUnknownRows(PersonTypeName)
	}

	func select(where whereClause: String = "", arguments: [Any?] = []) throws -> [PersonRow] {
		var query = "SELECT id, at_ns, data FROM " + PersonTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try q.withRows(query, arguments: arguments) { rows in
			var result: [PersonRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Person(serializedBytes: dataBytes)
				result.append(PersonRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
	}

	func insert(_ data: Generatedtest_Example_Person) throws -> PersonRow {
		let id = try uuidV7()
		try validateUUID(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	func insertWithID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		try validateForWrite(data)
		let dataBytes = try data.serializedData()
		var atNs: Int64 = 0
		var insertArguments: [Any?] = [id, atNs, dataBytes]
		insertArguments.append(data.name)
		insertArguments.append(data.age)
		try q.withTransaction { transaction in
			atNs = try nextObjectAtNs(transaction, tableName: PersonTableName, objectID: id)
			insertArguments[1] = atNs
			try transaction.execute("DELETE FROM \(_deletedTableName) WHERE table_name = ? AND id = ?", arguments: [PersonTableName, id])
			try transaction.execute(PersonInsertSQL, arguments: insertArguments)
		}
		return PersonRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		try validateForWrite(data)
		let dataBytes = try data.serializedData()
		var atNs: Int64 = 0
		var updateArguments: [Any?] = [id, atNs, dataBytes]
		updateArguments.append(data.name)
		updateArguments.append(data.age)
		try q.withTransaction { transaction in
			atNs = try nextObjectAtNs(transaction, tableName: PersonTableName, objectID: id)
			updateArguments[1] = atNs
			try transaction.execute("DELETE FROM \(_deletedTableName) WHERE table_name = ? AND id = ?", arguments: [PersonTableName, id])
			try transaction.execute(PersonUpsertSQL, arguments: updateArguments)
		}
		return PersonRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: PersonRow) throws -> PersonRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try q.withTransaction { transaction in
			let atNs = try nextObjectAtNs(transaction, tableName: PersonTableName, objectID: id)
			try transaction.execute("INSERT INTO \(_deletedTableName) (table_name, id, at_ns) VALUES (?, ?, ?) ON CONFLICT(table_name, id) DO UPDATE SET at_ns = excluded.at_ns", arguments: [PersonTableName, id, atNs])
			try transaction.execute("DELETE FROM " + PersonTableNameQuoted + " WHERE id = ?", arguments: [id])
		}
	}

	func deleteRow(_ row: PersonRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Person) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataBytes = try data.serializedData()
		try q.execute("DELETE FROM \(_deletedTableName) WHERE table_name = ? AND id = ?", arguments: [PersonTableName, id])
		var upsertArguments: [Any?] = [id, atNs, dataBytes]
		upsertArguments.append(data.name)
		upsertArguments.append(data.age)
		try q.execute(PersonUpsertSQL, arguments: upsertArguments)
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try q.execute("INSERT INTO \(_deletedTableName) (table_name, id, at_ns) VALUES (?, ?, ?) ON CONFLICT(table_name, id) DO UPDATE SET at_ns = excluded.at_ns", arguments: [PersonTableName, id, atNs])
		try q.execute("DELETE FROM " + PersonTableNameQuoted + " WHERE id = ?", arguments: [id])
	}

	private func reproject() throws {
		let rowsToReproject = try q.withRows("SELECT id, data FROM " + PersonTableNameQuoted) { rows in
			var buffered: [(String, Data)] = []
			while let row = try rows.next() {
				buffered.append((try row.string(at: 0), try row.data(at: 1)))
			}
			return buffered
		}
		for (id, dataBytes) in rowsToReproject {
			let data = try Generatedtest_Example_Person(serializedBytes: dataBytes)
			var reprojectArguments: [Any?] = []
			reprojectArguments.append(data.name)
			reprojectArguments.append(data.age)
			reprojectArguments.append(id)
			try q.execute(PersonReprojectSQL, arguments: reprojectArguments)
		}
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		try replayUnknownByType(q, typeName: typeName) { record in
			if record.deleted {
				try tombstoneWithAtNs(id: record.id, atNs: record.atNs)
				return
			}
			let data = try decodeAnyJSON(record.data, as: Generatedtest_Example_Person.self)
			try upsertWithAtNs(id: record.id, atNs: record.atNs, data: data)
		}
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(PersonTypeName)
	}

}

let NoteTableName = "generatedtest_example_note"
private let NoteTableNameQuoted = quoteSQLiteIdentifier(NoteTableName)
let NoteTypeName = "generatedtest.example.Note"
let NoteProjectionSchema = "text:string"
private let NoteCreateTableSQL = "CREATE TABLE IF NOT EXISTS \"generatedtest_example_note\" (\"id\" TEXT PRIMARY KEY, \"at_ns\" INTEGER NOT NULL, \"data\" BLOB NOT NULL, \"text\" TEXT NOT NULL DEFAULT '')"
private let NoteInsertSQL = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?)"
private let NoteUpsertSQL = "INSERT INTO \"generatedtest_example_note\" (\"id\", \"at_ns\", \"data\", \"text\") VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET \"at_ns\" = excluded.\"at_ns\", \"data\" = excluded.\"data\", \"text\" = excluded.\"text\""
private let NoteGeneratedIndexPrefix = "idx_generatedtest_example_note__"
private let NoteReprojectSQL = "UPDATE \"generatedtest_example_note\" SET \"text\" = ? WHERE id = ?"

struct NoteRow: Equatable, Sendable {
	var id: String
	var atNs: Int64
	var data: Generatedtest_Example_Note
	init(id: String, atNs: Int64, data: Generatedtest_Example_Note) {
		self.id = id
		self.atNs = atNs
		self.data = data
	}
}

struct NoteTable {
	fileprivate let q: any DBTX
	init(_ q: any DBTX) {
		self.q = q
	}

	func initialize() throws {
		try ensureCoreTables(q)
		try q.execute(NoteCreateTableSQL)
		let existingColumns = try q.withRows("PRAGMA table_info(\"\(NoteTableName)\")") { rows in
			var columns = Set<String>()
			while let row = try rows.next() {
				columns.insert(try row.string(at: 1))
			}
			return columns
		}
		if !existingColumns.contains("text") {
			try q.execute("ALTER TABLE " + NoteTableNameQuoted + " ADD COLUMN \"text\" TEXT NOT NULL DEFAULT ''")
		}
		try ensureManagedIndexes(q, tableName: NoteTableName, generatedIndexPrefix: NoteGeneratedIndexPrefix, createIndexSQL: [
		], desiredIndexNames: [
		])
		let currentSchema = try q.withRows("SELECT schema_hash FROM \(_proprdbSchemaTableName) WHERE table_name = ?", arguments: [NoteTableName]) { rows -> String? in
			if let row = try rows.next() {
				return try row.string(at: 0)
			}
			return nil as String?
		}
		if let currentSchema, currentSchema != NoteProjectionSchema {
			try reproject()
			try q.execute("UPDATE \(_proprdbSchemaTableName) SET schema_hash = ? WHERE table_name = ?", arguments: [NoteProjectionSchema, NoteTableName])
		} else if currentSchema == nil {
			try q.execute("INSERT INTO \(_proprdbSchemaTableName) (table_name, schema_hash) VALUES (?, ?)", arguments: [NoteTableName, NoteProjectionSchema])
		}
		try drainUnknownRows(NoteTypeName)
	}

	func select(where whereClause: String = "", arguments: [Any?] = []) throws -> [NoteRow] {
		var query = "SELECT id, at_ns, data FROM " + NoteTableNameQuoted
		if !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
			query += " WHERE " + whereClause
		}
		return try q.withRows(query, arguments: arguments) { rows in
			var result: [NoteRow] = []
			while let row = try rows.next() {
				let id = try row.string(at: 0)
				let atNs = try row.int64(at: 1)
				let dataBytes = try row.data(at: 2)
				let data = try Generatedtest_Example_Note(serializedBytes: dataBytes)
				result.append(NoteRow(id: id, atNs: atNs, data: data))
			}
			return result
		}
	}

	func insert(_ data: Generatedtest_Example_Note) throws -> NoteRow {
		let id = try uuidV7()
		try validateUUID(id)
		return try insertWithIDInternal(id: id, data: data)
	}

	private func insertWithIDInternal(id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		let dataBytes = try data.serializedData()
		var atNs: Int64 = 0
		var insertArguments: [Any?] = [id, atNs, dataBytes]
		insertArguments.append(data.text)
		try q.withTransaction { transaction in
			atNs = try nextObjectAtNs(transaction, tableName: NoteTableName, objectID: id)
			insertArguments[1] = atNs
			try transaction.execute("DELETE FROM \(_deletedTableName) WHERE table_name = ? AND id = ?", arguments: [NoteTableName, id])
			try transaction.execute(NoteInsertSQL, arguments: insertArguments)
		}
		return NoteRow(id: id, atNs: atNs, data: data)
	}

	func updateByID(_ id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try validateUUID(id)
		let dataBytes = try data.serializedData()
		var atNs: Int64 = 0
		var updateArguments: [Any?] = [id, atNs, dataBytes]
		updateArguments.append(data.text)
		try q.withTransaction { transaction in
			atNs = try nextObjectAtNs(transaction, tableName: NoteTableName, objectID: id)
			updateArguments[1] = atNs
			try transaction.execute("DELETE FROM \(_deletedTableName) WHERE table_name = ? AND id = ?", arguments: [NoteTableName, id])
			try transaction.execute(NoteUpsertSQL, arguments: updateArguments)
		}
		return NoteRow(id: id, atNs: atNs, data: data)
	}

	func updateRow(_ row: NoteRow) throws -> NoteRow {
		return try updateByID(row.id, data: row.data)
	}

	func deleteByID(_ id: String) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try q.withTransaction { transaction in
			let atNs = try nextObjectAtNs(transaction, tableName: NoteTableName, objectID: id)
			try transaction.execute("INSERT INTO \(_deletedTableName) (table_name, id, at_ns) VALUES (?, ?, ?) ON CONFLICT(table_name, id) DO UPDATE SET at_ns = excluded.at_ns", arguments: [NoteTableName, id, atNs])
			try transaction.execute("DELETE FROM " + NoteTableNameQuoted + " WHERE id = ?", arguments: [id])
		}
	}

	func deleteRow(_ row: NoteRow) throws {
		try deleteByID(row.id)
	}

	fileprivate func upsertWithAtNs(id: String, atNs: Int64, data: Generatedtest_Example_Note) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		let dataBytes = try data.serializedData()
		try q.execute("DELETE FROM \(_deletedTableName) WHERE table_name = ? AND id = ?", arguments: [NoteTableName, id])
		var upsertArguments: [Any?] = [id, atNs, dataBytes]
		upsertArguments.append(data.text)
		try q.execute(NoteUpsertSQL, arguments: upsertArguments)
	}

	fileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {
		if id.isEmpty {
			throw ProprDBError("empty id")
		}
		try q.execute("INSERT INTO \(_deletedTableName) (table_name, id, at_ns) VALUES (?, ?, ?) ON CONFLICT(table_name, id) DO UPDATE SET at_ns = excluded.at_ns", arguments: [NoteTableName, id, atNs])
		try q.execute("DELETE FROM " + NoteTableNameQuoted + " WHERE id = ?", arguments: [id])
	}

	private func reproject() throws {
		let rowsToReproject = try q.withRows("SELECT id, data FROM " + NoteTableNameQuoted) { rows in
			var buffered: [(String, Data)] = []
			while let row = try rows.next() {
				buffered.append((try row.string(at: 0), try row.data(at: 1)))
			}
			return buffered
		}
		for (id, dataBytes) in rowsToReproject {
			let data = try Generatedtest_Example_Note(serializedBytes: dataBytes)
			var reprojectArguments: [Any?] = []
			reprojectArguments.append(data.text)
			reprojectArguments.append(id)
			try q.execute(NoteReprojectSQL, arguments: reprojectArguments)
		}
	}

	fileprivate func drainUnknownRows(_ typeName: String) throws {
		try replayUnknownByType(q, typeName: typeName) { record in
			if record.deleted {
				try tombstoneWithAtNs(id: record.id, atNs: record.atNs)
				return
			}
			let data = try decodeAnyJSON(record.data, as: Generatedtest_Example_Note.self)
			try upsertWithAtNs(id: record.id, atNs: record.atNs, data: data)
		}
	}

	func drainUnknownRows() throws {
		try drainUnknownRows(NoteTypeName)
	}

}

struct CRUD {
	let person: PersonTable
	let note: NoteTable
	init(_ q: any DBTX) {
		self.person = PersonTable(q)
		self.note = NoteTable(q)
	}

	func tableDescriptors() -> [GeneratedTableDescriptor] {
		return [
			GeneratedTableDescriptor(tableName: PersonTableName, typeName: PersonTypeName, isCore: false, syncEnabled: true),
			GeneratedTableDescriptor(tableName: NoteTableName, typeName: NoteTypeName, isCore: false, syncEnabled: false),
			GeneratedTableDescriptor(tableName: coreTableDeletedName, typeName: "", isCore: true, syncEnabled: false),
			GeneratedTableDescriptor(tableName: coreTableSyncName, typeName: "", isCore: true, syncEnabled: false),
			GeneratedTableDescriptor(tableName: coreTableSchemaStateName, typeName: "", isCore: true, syncEnabled: false),
			GeneratedTableDescriptor(tableName: coreTableUnknownName, typeName: "", isCore: true, syncEnabled: false),
		]
	}

	private func dbtx() -> any DBTX {
		return person.q
	}

	func initialize() throws {
		try person.initialize()
		try note.initialize()
	}

	func writeJSONL(remote: String) throws -> String {
		let q = dbtx()
		var output = ""
		for row in try person.select() {
			if !(try syncNeedsSend(q, objectID: row.id, tableName: PersonTableName, remote: remote, atNs: row.atNs)) {
				continue
			}
			let dataJSON = try marshalAnyJSON(row.data, typeName: PersonTypeName)
			output += try encodeJSONLRecord(JSONLRecord(id: row.id, deleted: false, atNs: row.atNs, data: dataJSON))
			try syncUpsert(q, objectID: row.id, tableName: PersonTableName, remote: remote, atNs: row.atNs)
		}
		try q.withRows("SELECT table_name, id, at_ns FROM \(_deletedTableName) WHERE table_name IN (?)", arguments: [PersonTableName]) { rows in
			while let row = try rows.next() {
				let tableName = try row.string(at: 0)
				let id = try row.string(at: 1)
				let atNs = try row.int64(at: 2)
				if !(try syncNeedsSend(q, objectID: id, tableName: tableName, remote: remote, atNs: atNs)) {
					continue
				}
				let typeName: String
				switch tableName {
				case PersonTableName:
					typeName = PersonTypeName
				default:
					throw ProprDBError("unsupported tombstone table \(tableName)")
				}
				let dataJSON = try marshalTypeOnlyAnyJSON(typeName: typeName)
				output += try encodeJSONLRecord(JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))
				try syncUpsert(q, objectID: id, tableName: tableName, remote: remote, atNs: atNs)
			}
		}
		return output
	}

	func readJSONL(remote: String, text: String) throws {
		let q = dbtx()
		var readError: Error?
		do {
			try ProprDBSwiftRuntime.readJSONL(text: text) { record, lineNumber in
				if record.id.isEmpty {
					throw ProprDBError("jsonl line \(lineNumber) has empty id")
				}
				if record.data.isEmpty {
					throw ProprDBError("jsonl line \(lineNumber) has empty data")
				}
				let typeName = try typeNameFromAnyJSON(record.data)
				switch typeName {
				case PersonTypeName:
					let localMax = try localMaxAtNs(q, tableName: PersonTableName, objectID: record.id)
					try syncUpsert(q, objectID: record.id, tableName: PersonTableName, remote: remote, atNs: record.atNs)
					if record.atNs < localMax {
						return
					}
					if record.deleted {
						try person.tombstoneWithAtNs(id: record.id, atNs: record.atNs)
						return
					}
					let data = try decodeAnyJSON(record.data, as: Generatedtest_Example_Person.self)
					try person.upsertWithAtNs(id: record.id, atNs: record.atNs, data: data)
					return
				case NoteTypeName:
					logIgnoredUnsyncedJSONLRecord(typeName: typeName, id: record.id, remote: remote, lineNumber: lineNumber)
					return
				default:
					try unknownInsert(q, typeName: typeName, record: record)
				}
			}
		} catch {
			readError = error
		}
		do {
			try compactUnknownLatest(q)
		} catch {
			if let readError {
				throw ProprDBError("read jsonl: \(readError) (additionally, compact unknown rows: \(error))")
			}
			throw error
		}
		if let readError {
			throw readError
		}
	}
}

extension ProprDBActor {
	func initialize() throws {
		try withDatabase { database in try CRUD(database).initialize() }
	}

	func selectPerson() throws -> [PersonRow] {
		try withDatabase { database in try PersonTable(database).select() }
	}

	func insertPerson(_ data: Generatedtest_Example_Person) throws -> PersonRow {
		try withDatabase { database in try PersonTable(database).insert(data) }
	}

	func updatePersonByID(_ id: String, data: Generatedtest_Example_Person) throws -> PersonRow {
		try withDatabase { database in try PersonTable(database).updateByID(id, data: data) }
	}

	func deletePersonByID(_ id: String) throws {
		try withDatabase { database in try PersonTable(database).deleteByID(id) }
	}

	func selectNote() throws -> [NoteRow] {
		try withDatabase { database in try NoteTable(database).select() }
	}

	func insertNote(_ data: Generatedtest_Example_Note) throws -> NoteRow {
		try withDatabase { database in try NoteTable(database).insert(data) }
	}

	func updateNoteByID(_ id: String, data: Generatedtest_Example_Note) throws -> NoteRow {
		try withDatabase { database in try NoteTable(database).updateByID(id, data: data) }
	}

	func deleteNoteByID(_ id: String) throws {
		try withDatabase { database in try NoteTable(database).deleteByID(id) }
	}

	func writeJSONL(remote: String) throws -> String {
		try withDatabase { database in try CRUD(database).writeJSONL(remote: remote) }
	}

	func readJSONL(remote: String, text: String) throws {
		try withDatabase { database in try CRUD(database).readJSONL(remote: remote, text: text) }
	}
}
