package proprdbgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	rustRuntime = "::proprdb_runtime"
)

type rustModel struct {
	model   messageModel
	message *protogen.Message
}

type rustEmitter struct{ g *protogen.GeneratedFile }

func GenerateRustFiles(plugin *protogen.Plugin, files []*protogen.File) (err error) {
	if len(files) == 0 {
		return nil
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Desc.Path() < files[j].Desc.Path() })
	collector := modelCollector{}
	models := make([]messageModel, 0)
	rustModels := make([]rustModel, 0)
	for _, file := range files {
		fileModels, err := collector.collectModels(file)
		if err != nil {
			return err
		}
		for i := range fileModels {
			fileModels[i].GoName = rustCamel(fileModels[i].GoName)
			fileModels[i].TableTypeName = fileModels[i].GoName + "Table"
			fileModels[i].RowTypeName = fileModels[i].GoName + "Row"
		}
		models = append(models, fileModels...)
		messages := make(map[string]*protogen.Message)
		collectRustMessages(messages, file.Messages)
		for _, model := range fileModels {
			rustModels = append(rustModels, rustModel{model, messages[model.TypeName]})
		}
	}
	if len(models) == 0 {
		return nil
	}
	if err := validateModels(models); err != nil {
		return err
	}
	owners := make(map[string]string)
	for _, model := range rustModels {
		for _, symbol := range []string{model.model.GoName, rustSnake(model.model.GoName)} {
			if owner, exists := owners[symbol]; exists {
				return fmt.Errorf("generated Rust symbol %s collides between %s and %s", symbol, owner, model.model.TypeName)
			}
			owners[symbol] = model.model.TypeName
		}
	}
	g := plugin.NewGeneratedFile(files[0].GeneratedFilenamePrefix+".proprdb.pb.rs", "")
	g.P("// Code generated by protoc-gen-proprdb-rust. DO NOT EDIT.")
	descriptorBytes, err := rustDescriptors(plugin, files)
	if err != nil {
		return fmt.Errorf("marshal Rust descriptors: %w", err)
	}
	var encoded strings.Builder
	for _, value := range descriptorBytes {
		fmt.Fprintf(&encoded, "\\x%02x", value)
	}
	g.P("const DESCRIPTOR_BYTES: &[u8] = b\"", encoded.String(), "\";")
	g.P("fn descriptor_pool() -> ", rustRuntime, "::Result<", rustRuntime, "::DescriptorPool> {")
	g.P("static POOL: ::std::sync::OnceLock<", rustRuntime, "::DescriptorPool> = ::std::sync::OnceLock::new();")
	g.P("if let Some(pool) = POOL.get() { return Ok(pool.clone()); }")
	g.P("let pool = ", rustRuntime, "::DescriptorPool::decode(DESCRIPTOR_BYTES)?;")
	g.P("Ok(POOL.get_or_init(|| pool).clone()) }")
	emitter := rustEmitter{g}
	for _, model := range rustModels {
		emitter.emitModel(model)
	}
	g.P("pub struct Crud<'a> {")
	for _, model := range rustModels {
		g.P("pub ", rustIdent(rustSnake(model.model.GoName)), ": ", rustRuntime, "::Table<'a, ", model.model.GoName, "Model>,")
	}
	g.P("}")
	g.P("impl<'a> Crud<'a> {")
	g.P("pub fn new(connection: &'a ", rustRuntime, "::Connection) -> Self { Self {")
	for _, model := range rustModels {
		g.P(rustIdent(rustSnake(model.model.GoName)), ": ", rustRuntime, "::Table::new(connection),")
	}
	g.P("} }")
	g.P("fn tables(&self) -> Vec<&dyn ", rustRuntime, "::SyncTable> { vec![")
	for _, model := range rustModels {
		g.P("&self.", rustIdent(rustSnake(model.model.GoName)), ",")
	}
	g.P("] }")
	g.P("pub fn initialize(&self) -> ", rustRuntime, "::Result<()> { ", rustRuntime, "::initialize_tables(&self.tables()) }")
	g.P("pub fn read_jsonl(&self, remote: &str, reader: impl ::std::io::BufRead) -> ", rustRuntime, "::Result<()> { ", rustRuntime, "::read_jsonl(&self.tables(), remote, reader) }")
	g.P("pub fn prepare_jsonl(&self, remote: &str, writer: impl ::std::io::Write) -> ", rustRuntime, "::Result<", rustRuntime, "::JsonlCheckpoint> { ", rustRuntime, "::prepare_jsonl(&self.tables(), remote, writer) }")
	g.P("pub fn write_jsonl(&self, remote: &str, writer: impl ::std::io::Write) -> ", rustRuntime, "::Result<()> { ", rustRuntime, "::write_jsonl(&self.tables(), remote, writer) }")
	firstTable := "self." + rustIdent(rustSnake(rustModels[0].model.GoName))
	for _, operation := range []string{"acknowledge_jsonl", "discard_jsonl"} {
		g.P("pub fn ", operation, "(&self, checkpoint: &", rustRuntime, "::JsonlCheckpoint) -> ", rustRuntime, "::Result<()> { ", rustRuntime, "::", operation, "(", rustRuntime, "::SyncTable::connection(&", firstTable, "), checkpoint) }")
	}
	g.P("pub fn introspect_tables(&self) -> ", rustRuntime, "::Result<Vec<", rustRuntime, "::TableIntrospection>> { ", rustRuntime, "::SyncTable::introspect_all(&", firstTable, ", &self.tables()) }")
	g.P("}")
	return nil
}

func collectRustMessages(messages map[string]*protogen.Message, list []*protogen.Message) {
	for _, message := range list {
		messages[string(message.Desc.FullName())] = message
		collectRustMessages(messages, message.Messages)
	}
}

func rustWords(value string) []string {
	chars := []rune(value)
	words := make([]string, 0)
	start := 0
	for i, char := range chars {
		if char == '_' || char == '.' {
			if i > start {
				words = append(words, strings.ToLower(string(chars[start:i])))
			}
			start = i + 1
			continue
		}
		if i > start && unicode.IsUpper(char) && (unicode.IsLower(chars[i-1]) || unicode.IsDigit(chars[i-1]) || (i+1 < len(chars) && unicode.IsLower(chars[i+1]) && unicode.IsUpper(chars[i-1]))) {
			words = append(words, strings.ToLower(string(chars[start:i])))
			start = i
		}
	}
	if start < len(chars) {
		words = append(words, strings.ToLower(string(chars[start:])))
	}
	return words
}

func rustSnake(value string) string { return strings.Join(rustWords(value), "_") }
func rustCamel(value string) string {
	var result strings.Builder
	for _, word := range rustWords(value) {
		result.WriteString(strings.ToUpper(word[:1]) + word[1:])
	}
	return result.String()
}

func rustIdent(value string) string {
	switch value {
	case "self", "super", "crate", "Self":
		return value + "_"
	case "as", "async", "await", "break", "const", "continue", "dyn", "else", "enum", "extern", "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while", "abstract", "become", "box", "do", "final", "macro", "override", "priv", "try", "typeof", "unsized", "virtual", "yield":
		return "r#" + value
	default:
		return value
	}
}

func rustMessagePath(message *protogen.Message) string {
	parts := []string{"crate"}
	for _, part := range strings.Split(string(message.Desc.ParentFile().Package()), ".") {
		if part != "" {
			parts = append(parts, rustIdent(rustSnake(part)))
		}
	}
	parents := make([]string, 0)
	for parent := message.Desc.Parent(); parent != nil; parent = parent.Parent() {
		if _, ok := parent.(protoreflect.MessageDescriptor); !ok {
			break
		}
		parents = append(parents, rustIdent(rustSnake(string(parent.Name()))))
	}
	for i := len(parents) - 1; i >= 0; i-- {
		parts = append(parts, parents[i])
	}
	parts = append(parts, rustIdent(rustCamel(string(message.Desc.Name()))))
	return strings.Join(parts, "::")
}

func rustValue(field *protogen.Field, expression string) string {
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return rustRuntime + "::Value::Text(" + expression + ".clone())"
	case protoreflect.BytesKind:
		return rustRuntime + "::Value::Blob(" + expression + ".clone())"
	case protoreflect.DoubleKind:
		return rustRuntime + "::Value::Real(" + expression + ")"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return rustRuntime + "::Value::Integer(" + expression + ")"
	case protoreflect.FloatKind:
		return rustRuntime + "::Value::Real(f64::from(" + expression + "))"
	default:
		return rustRuntime + "::Value::Integer(i64::from(" + expression + "))"
	}
}

func rustBorrowedValue(field *protogen.Field) string {
	if field.Desc.Kind() == protoreflect.StringKind || field.Desc.Kind() == protoreflect.BytesKind {
		return rustValue(field, "value")
	}
	return rustValue(field, "*value")
}

func (e rustEmitter) emitProjection(message *protogen.Message, field *protogen.Field) {
	g := e.g
	name := rustIdent(rustSnake(string(field.Desc.Name())))
	switch {
	case field.Oneof != nil && !field.Oneof.Desc.IsSynthetic():
		messagePath := rustMessagePath(message)
		modulePath := messagePath[:strings.LastIndex(messagePath, "::")] + "::" + rustIdent(rustSnake(string(message.Desc.Name())))
		variant := modulePath + "::" + rustCamel(string(field.Oneof.Desc.Name())) + "::" + rustCamel(string(field.Desc.Name()))
		g.P("match &data.", rustIdent(rustSnake(string(field.Oneof.Desc.Name()))), " { Some(", variant, "(value)) => ", rustBorrowedValue(field), ", _ => ", rustRuntime, "::Value::Null },")
	case field.Desc.HasPresence():
		g.P("data.", name, ".as_ref().map_or(", rustRuntime, "::Value::Null, |value| ", rustBorrowedValue(field), "),")
	default:
		g.P(rustValue(field, "data."+name), ",")
	}
}

func (e rustEmitter) emitPathProjection(message *protogen.Message, path []*protogen.Field, expression string) {
	field := path[0]
	name := rustIdent(rustSnake(string(field.Desc.Name())))
	leaf := len(path) == 1
	switch {
	case field.Oneof != nil && !field.Oneof.Desc.IsSynthetic():
		messagePath := rustMessagePath(message)
		modulePath := messagePath[:strings.LastIndex(messagePath, "::")] + "::" + rustIdent(rustSnake(string(message.Desc.Name())))
		variant := modulePath + "::" + rustCamel(string(field.Oneof.Desc.Name())) + "::" + rustCamel(string(field.Desc.Name()))
		e.g.P("match &", expression, ".", rustIdent(rustSnake(string(field.Oneof.Desc.Name()))), " { Some(", variant, "(value)) => {")
	case field.Desc.HasPresence():
		e.g.P(expression, ".", name, ".as_ref().map_or(", rustRuntime, "::Value::Null, |value| {")
	default:
		e.g.P(rustValue(field, expression+"."+name))
		return
	}
	if leaf {
		e.g.P(rustBorrowedValue(field))
	} else {
		e.emitPathProjection(field.Message, path[1:], "value")
	}
	if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
		e.g.P("}, _ => ", rustRuntime, "::Value::Null }")
	} else {
		e.g.P("})")
	}
}

func (e rustEmitter) emitModel(model rustModel) {
	g := e.g
	m := model.model
	path := rustMessagePath(model.message)
	g.P("pub struct ", m.GoName, "Model;")
	g.P("pub type ", m.RowTypeName, " = ", rustRuntime, "::Row<", path, ">;")
	g.P("pub type ", m.TableTypeName, "<'a> = ", rustRuntime, "::Table<'a, ", m.GoName, "Model>;")
	g.P("impl ", rustRuntime, "::Model for ", m.GoName, "Model {")
	g.P("type Data = ", path, ";")
	g.P("fn descriptor() -> ", rustRuntime, "::Result<", rustRuntime, "::MessageDescriptor> { descriptor_pool()?.get_message_by_name(Self::TYPE_NAME).ok_or_else(|| ", rustRuntime, "::Error::Invalid(format!(\"missing descriptor {}\", Self::TYPE_NAME))) }")
	for _, entry := range []struct{ name, value string }{{"TABLE_NAME", m.TableName}, {"TYPE_NAME", m.TypeName}, {"PROJECTION_SCHEMA", m.ProjectionSchema}, {"CREATE_TABLE_SQL", m.createTableSQL()}, {"INSERT_SQL", m.insertSQL(false)}, {"UPSERT_SQL", m.insertSQL(true)}, {"INDEX_PREFIX", m.generatedIndexPrefix()}} {
		g.P("const ", entry.name, ": &str = ", strconv.Quote(entry.value), ";")
	}
	g.P("const SYNC_ENABLED: bool = ", !m.OmitSync, ";")
	g.P("const CHANGE_LISTENERS: bool = ", m.ChangeListeners, ";")
	g.P("const QUERY_STATISTICS: bool = ", m.QueryStatistics, ";")
	g.P("const COLUMNS: &[", rustRuntime, "::Column] = &[")
	for _, field := range m.ProjectedFields {
		g.P(rustRuntime, "::Column { name: ", strconv.Quote(field.ColumnName), ", definition: ", strconv.Quote(field.createColumnSQL()), ", legacy_oneof_presence_repair: ", field.LegacyOneofPresenceRepair, " },")
	}
	g.P("];")
	g.P("const INDEXES: &[&str] = &[")
	for _, index := range m.Indexes {
		g.P(strconv.Quote(m.createIndexSQL(index)), ",")
	}
	g.P("];")
	if m.ValidateWrite {
		g.P("fn validate(data: &Self::Data) -> ", rustRuntime, "::Result<()> { data.valid() }")
	}
	dataName := dataVariable
	if len(m.ProjectedFields) == 0 {
		dataName = "_data"
	}
	g.P("fn projected_values(", dataName, ": &Self::Data) -> Vec<", rustRuntime, "::Value> { vec![")
	for _, projection := range m.ProjectedFields {
		if len(projection.Path) > 0 {
			e.emitPathProjection(model.message, projection.Path, "data")
			g.P(",")
			continue
		}
		for _, field := range model.message.Fields {
			if string(field.Desc.Name()) == projection.ProtoFieldName {
				e.emitProjection(model.message, field)
			}
		}
	}
	g.P("] }")
	g.P("}")
	if m.AllowCustomIDInsert {
		g.P("impl ", rustRuntime, "::CustomIdModel for ", m.GoName, "Model {}")
	}
}
