package proprdbgen

import (
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
)

const swiftRuntimeModuleName = "ProprDBSwiftRuntime"

type swiftEmitter struct {
	g *protogen.GeneratedFile
}

// GenerateSwiftFile generates proprdb CRUD code for Swift.
func GenerateSwiftFile(plugin *protogen.Plugin, file *protogen.File) error {
	collector := modelCollector{}
	models, err := collector.collectModels(file)
	if err != nil {
		return err
	}
	if len(models) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + ".proprdb.pb.swift"
	g := plugin.NewGeneratedFile(filename, "")
	g.P("// Code generated by protoc-gen-proprdb-swift. DO NOT EDIT.")
	g.P()
	g.P("import Foundation")
	g.P("import SwiftProtobuf")
	g.P("import ", swiftRuntimeModuleName)
	g.P()

	emitter := swiftEmitter{g: g}
	for _, model := range models {
		emitter.emitModel(file, model)
	}
	emitter.emitWrapper(file, models)
	return nil
}

func (e swiftEmitter) emitModel(file *protogen.File, model messageModel) {
	g := e.g
	swiftTypeName := swiftMessageTypeName(file, model.GoName)
	tableNameConst := model.GoName + "TableName"
	typeNameConst := model.GoName + "TypeName"
	schemaConst := model.GoName + "ProjectionSchema"
	createTableConst := model.GoName + "CreateTableSQL"
	insertConst := model.GoName + "InsertSQL"
	upsertConst := model.GoName + "UpsertSQL"
	reprojectConst := model.GoName + "ReprojectSQL"
	indexPrefixConst := model.GoName + "GeneratedIndexPrefix"

	g.P("let ", tableNameConst, " = ", strconv.Quote(model.TableName))
	g.P("private let ", tableNameConst, "Quoted = quoteSQLiteIdentifier(", tableNameConst, ")")
	g.P("let ", typeNameConst, " = ", strconv.Quote(model.TypeName))
	g.P("let ", schemaConst, " = ", strconv.Quote(model.ProjectionSchema))
	g.P("private let ", createTableConst, " = ", strconv.Quote(model.createTableSQL()))
	g.P("private let ", insertConst, " = ", strconv.Quote(model.insertSQL(false)))
	g.P("private let ", upsertConst, " = ", strconv.Quote(model.insertSQL(true)))
	g.P("private let ", indexPrefixConst, " = ", strconv.Quote(model.generatedIndexPrefix()))
	for indexPosition, indexModel := range model.Indexes {
		g.P("private let ", model.GoName, "CreateIndexSQL", strconv.Itoa(indexPosition+1), " = ", strconv.Quote(model.createIndexSQL(indexModel)))
	}
	if len(model.ProjectedFields) > 0 {
		g.P("private let ", reprojectConst, " = ", strconv.Quote(model.reprojectSQL()))
	}
	g.P()

	g.P("struct ", model.RowTypeName, ": Equatable {")
	g.P("\tvar id: String")
	g.P("\tvar atNs: Int64")
	g.P("\tvar data: ", swiftTypeName)
	g.P("\tinit(id: String, atNs: Int64, data: ", swiftTypeName, ") {")
	g.P("\t\tself.id = id")
	g.P("\t\tself.atNs = atNs")
	g.P("\t\tself.data = data")
	g.P("\t}")
	g.P("}")
	g.P()

	g.P("struct ", model.TableTypeName, " {")
	g.P("\tfileprivate let q: any DBTX")
	g.P("\tinit(_ q: any DBTX) {")
	g.P("\t\tself.q = q")
	g.P("\t}")
	g.P()

	e.emitSwiftInitMethod(file, model, swiftTypeName, tableNameConst, typeNameConst, schemaConst, createTableConst, indexPrefixConst)
	e.emitSwiftSelectMethod(model, swiftTypeName, tableNameConst)
	e.emitSwiftInsertMethod(model, swiftTypeName, tableNameConst, insertConst)
	e.emitSwiftUpdateMethod(model, swiftTypeName, tableNameConst, upsertConst)
	e.emitSwiftDeleteMethod(model, tableNameConst)
	e.emitSwiftApplyWithAtNsMethods(model, swiftTypeName, tableNameConst, upsertConst)
	if len(model.ProjectedFields) > 0 {
		e.emitSwiftReprojectMethod(file, model, swiftTypeName, tableNameConst, reprojectConst)
	}
	e.emitSwiftDrainUnknownMethod(file, swiftTypeName, typeNameConst)
	g.P("}")
	g.P()
}

func (e swiftEmitter) emitSwiftInitMethod(file *protogen.File, model messageModel, swiftTypeName, tableNameConst, typeNameConst, schemaConst, createTableConst, indexPrefixConst string) {
	g := e.g
	g.P("\tfunc initialize() throws {")
	g.P("\t\ttry ensureCoreTables(q)")
	g.P("\t\ttry q.execute(", createTableConst, ")")
	if len(model.ProjectedFields) > 0 {
		g.P("\t\tlet existingColumns = try q.withRows(\"PRAGMA table_info(\\\"\\(", tableNameConst, ")\\\")\") { rows in")
		g.P("\t\t\tvar columns = Set<String>()")
		g.P("\t\t\twhile let row = try rows.next() {")
		g.P("\t\t\t\tcolumns.insert(try row.string(at: 1))")
		g.P("\t\t\t}")
		g.P("\t\t\treturn columns")
		g.P("\t\t}")
		for _, projectedField := range model.ProjectedFields {
			g.P("\t\tif !existingColumns.contains(", strconv.Quote(projectedField.ColumnName), ") {")
			g.P("\t\t\ttry q.execute(\"ALTER TABLE \" + ", tableNameConst, "Quoted + \" ADD COLUMN ", escapeSwiftStringLiteralContent(projectedField.createColumnSQL()), "\")")
			g.P("\t\t}")
		}
	}

	g.P("\t\ttry ensureManagedIndexes(q, tableName: ", tableNameConst, ", generatedIndexPrefix: ", indexPrefixConst, ", createIndexSQL: [")
	for indexPosition := range model.Indexes {
		g.P("\t\t\t", model.GoName, "CreateIndexSQL", strconv.Itoa(indexPosition+1), ",")
	}
	g.P("\t\t], desiredIndexNames: [")
	for _, indexModel := range model.Indexes {
		g.P("\t\t\t", strconv.Quote(indexModel.IndexName), ",")
	}
	g.P("\t\t])")

	g.P("\t\tlet currentSchema = try q.withRows(\"SELECT schema_hash FROM \\(_proprdbSchemaTableName) WHERE table_name = ?\", arguments: [", tableNameConst, "]) { rows -> String? in")
	g.P("\t\t\tif let row = try rows.next() {")
	g.P("\t\t\t\treturn try row.string(at: 0)")
	g.P("\t\t\t}")
	g.P("\t\t\treturn nil as String?")
	g.P("\t\t}")
	g.P("\t\tif let currentSchema, currentSchema != ", schemaConst, " {")
	if len(model.ProjectedFields) > 0 {
		g.P("\t\t\ttry reproject()")
	}
	g.P("\t\t\ttry q.execute(\"UPDATE \\(_proprdbSchemaTableName) SET schema_hash = ? WHERE table_name = ?\", arguments: [", schemaConst, ", ", tableNameConst, "])")
	g.P("\t\t} else if currentSchema == nil {")
	g.P("\t\t\ttry q.execute(\"INSERT INTO \\(_proprdbSchemaTableName) (table_name, schema_hash) VALUES (?, ?)\", arguments: [", tableNameConst, ", ", schemaConst, "])")
	g.P("\t\t}")
	g.P("\t\ttry drainUnknownRows(", typeNameConst, ")")
	g.P("\t}")
	g.P()
	_ = swiftTypeName
	_ = file
}

func (e swiftEmitter) emitSwiftSelectMethod(model messageModel, swiftTypeName, tableNameConst string) {
	g := e.g
	g.P("\tfunc select(where whereClause: String = \"\", arguments: [Any?] = []) throws -> [", model.RowTypeName, "] {")
	g.P("\t\tvar query = \"SELECT id, at_ns, data FROM \" + ", tableNameConst, "Quoted")
	g.P("\t\tif !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {")
	g.P("\t\t\tquery += \" WHERE \" + whereClause")
	g.P("\t\t}")
	g.P("\t\treturn try q.withRows(query, arguments: arguments) { rows in")
	g.P("\t\t\tvar result: [", model.RowTypeName, "] = []")
	g.P("\t\t\twhile let row = try rows.next() {")
	g.P("\t\t\t\tlet id = try row.string(at: 0)")
	g.P("\t\t\t\tlet atNs = try row.int64(at: 1)")
	g.P("\t\t\t\tlet dataBytes = try row.data(at: 2)")
	g.P("\t\t\t\tlet data = try ", swiftTypeName, "(serializedBytes: dataBytes)")
	g.P("\t\t\t\tresult.append(", model.RowTypeName, "(id: id, atNs: atNs, data: data))")
	g.P("\t\t\t}")
	g.P("\t\t\treturn result")
	g.P("\t\t}")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftInsertMethod(model messageModel, swiftTypeName, tableNameConst, insertConst string) {
	g := e.g
	g.P("\tfunc insert(_ data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tlet id = try uuidV7()")
	g.P("\t\ttry validateUUID(id)")
	g.P("\t\treturn try insertWithIDInternal(id: id, data: data)")
	g.P("\t}")
	g.P()
	if model.AllowCustomIDInsert {
		g.P("\tfunc insertWithID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
		g.P("\t\treturn try insertWithIDInternal(id: id, data: data)")
		g.P("\t}")
		g.P()
	}
	g.P("\tprivate func insertWithIDInternal(id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry validateUUID(id)")
	if model.ValidateWrite {
		g.P("\t\ttry validateForWrite(data)")
	}
	g.P("\t\tlet atNs = nowNs()")
	g.P("\t\tlet dataBytes = try data.serializedData()")
	g.P("\t\ttry q.execute(\"DELETE FROM \\(_deletedTableName) WHERE table_name = ? AND id = ?\", arguments: [", tableNameConst, ", id])")
	g.P("\t\tvar insertArguments: [Any?] = [id, atNs, dataBytes]")
	for _, projectedField := range model.ProjectedFields {
		e.emitSwiftProjectedFieldAppend("insertArguments", "data", projectedField, "\t\t")
	}
	g.P("\t\ttry q.execute(", insertConst, ", arguments: insertArguments)")
	g.P("\t\treturn ", model.RowTypeName, "(id: id, atNs: atNs, data: data)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftUpdateMethod(model messageModel, swiftTypeName, tableNameConst, upsertConst string) {
	g := e.g
	g.P("\tfunc updateByID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry validateUUID(id)")
	if model.ValidateWrite {
		g.P("\t\ttry validateForWrite(data)")
	}
	g.P("\t\tlet atNs = nowNs()")
	g.P("\t\tlet dataBytes = try data.serializedData()")
	g.P("\t\ttry q.execute(\"DELETE FROM \\(_deletedTableName) WHERE table_name = ? AND id = ?\", arguments: [", tableNameConst, ", id])")
	g.P("\t\tvar updateArguments: [Any?] = [id, atNs, dataBytes]")
	for _, projectedField := range model.ProjectedFields {
		e.emitSwiftProjectedFieldAppend("updateArguments", "data", projectedField, "\t\t")
	}
	g.P("\t\ttry q.execute(", upsertConst, ", arguments: updateArguments)")
	g.P("\t\treturn ", model.RowTypeName, "(id: id, atNs: atNs, data: data)")
	g.P("\t}")
	g.P()
	g.P("\tfunc updateRow(_ row: ", model.RowTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\treturn try updateByID(row.id, data: row.data)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftDeleteMethod(model messageModel, tableNameConst string) {
	g := e.g
	g.P("\tfunc deleteByID(_ id: String) throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\tlet atNs = nowNs()")
	g.P("\t\ttry q.execute(\"INSERT INTO \\(_deletedTableName) (table_name, id, at_ns) VALUES (?, ?, ?) ON CONFLICT(table_name, id) DO UPDATE SET at_ns = excluded.at_ns\", arguments: [", tableNameConst, ", id, atNs])")
	g.P("\t\ttry q.execute(\"DELETE FROM \" + ", tableNameConst, "Quoted + \" WHERE id = ?\", arguments: [id])")
	g.P("\t}")
	g.P()
	g.P("\tfunc deleteRow(_ row: ", model.RowTypeName, ") throws {")
	g.P("\t\ttry deleteByID(row.id)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftApplyWithAtNsMethods(model messageModel, swiftTypeName, tableNameConst, upsertConst string) {
	g := e.g
	g.P("\tfileprivate func upsertWithAtNs(id: String, atNs: Int64, data: ", swiftTypeName, ") throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\tlet dataBytes = try data.serializedData()")
	g.P("\t\ttry q.execute(\"DELETE FROM \\(_deletedTableName) WHERE table_name = ? AND id = ?\", arguments: [", tableNameConst, ", id])")
	g.P("\t\tvar upsertArguments: [Any?] = [id, atNs, dataBytes]")
	for _, projectedField := range model.ProjectedFields {
		e.emitSwiftProjectedFieldAppend("upsertArguments", "data", projectedField, "\t\t")
	}
	g.P("\t\ttry q.execute(", upsertConst, ", arguments: upsertArguments)")
	g.P("\t}")
	g.P()
	g.P("\tfileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry q.execute(\"INSERT INTO \\(_deletedTableName) (table_name, id, at_ns) VALUES (?, ?, ?) ON CONFLICT(table_name, id) DO UPDATE SET at_ns = excluded.at_ns\", arguments: [", tableNameConst, ", id, atNs])")
	g.P("\t\ttry q.execute(\"DELETE FROM \" + ", tableNameConst, "Quoted + \" WHERE id = ?\", arguments: [id])")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftReprojectMethod(file *protogen.File, model messageModel, swiftTypeName, tableNameConst, reprojectConst string) {
	g := e.g
	g.P("\tprivate func reproject() throws {")
	g.P("\t\tlet rowsToReproject = try q.withRows(\"SELECT id, data FROM \" + ", tableNameConst, "Quoted) { rows in")
	g.P("\t\t\tvar buffered: [(String, Data)] = []")
	g.P("\t\t\twhile let row = try rows.next() {")
	g.P("\t\t\t\tbuffered.append((try row.string(at: 0), try row.data(at: 1)))")
	g.P("\t\t\t}")
	g.P("\t\t\treturn buffered")
	g.P("\t\t}")
	g.P("\t\tfor (id, dataBytes) in rowsToReproject {")
	g.P("\t\t\tlet data = try ", swiftTypeName, "(serializedBytes: dataBytes)")
	g.P("\t\t\tvar reprojectArguments: [Any?] = []")
	for _, projectedField := range model.ProjectedFields {
		e.emitSwiftProjectedFieldAppend("reprojectArguments", "data", projectedField, "\t\t\t")
	}
	g.P("\t\t\treprojectArguments.append(id)")
	g.P("\t\t\ttry q.execute(", reprojectConst, ", arguments: reprojectArguments)")
	g.P("\t\t}")
	g.P("\t}")
	g.P()
	_ = file
}

func (e swiftEmitter) emitSwiftDrainUnknownMethod(file *protogen.File, swiftTypeName, typeNameConst string) {
	g := e.g
	g.P("\tfileprivate func drainUnknownRows(_ typeName: String) throws {")
	g.P("\t\ttry replayUnknownByType(q, typeName: typeName) { record in")
	g.P("\t\t\tif record.deleted {")
	g.P("\t\t\t\ttry tombstoneWithAtNs(id: record.id, atNs: record.atNs)")
	g.P("\t\t\t\treturn")
	g.P("\t\t\t}")
	g.P("\t\t\tlet data = try decodeAnyJSON(record.data, as: ", swiftTypeName, ".self)")
	g.P("\t\t\ttry upsertWithAtNs(id: record.id, atNs: record.atNs, data: data)")
	g.P("\t\t}")
	g.P("\t}")
	g.P()
	g.P("\tfunc drainUnknownRows() throws {")
	g.P("\t\ttry drainUnknownRows(", typeNameConst, ")")
	g.P("\t}")
	g.P()
	_ = file
}

func (e swiftEmitter) emitSwiftProjectedFieldAppend(argumentsName, dataName string, projectedField projectedField, indent string) {
	g := e.g
	propertyName := swiftPropertyNameFromGoName(projectedField.GetterName[3:])
	if !projectedField.IsOptional {
		g.P(indent, argumentsName, ".append(", dataName, ".", propertyName, ")")
		return
	}
	presenceName := "has" + projectedField.GetterName[3:]
	g.P(indent, "if ", dataName, ".", presenceName, " {")
	g.P(indent, "\t", argumentsName, ".append(", dataName, ".", propertyName, ")")
	g.P(indent, "} else {")
	g.P(indent, "\t", argumentsName, ".append(nil)")
	g.P(indent, "}")
}

func (e swiftEmitter) emitWrapper(file *protogen.File, models []messageModel) {
	g := e.g
	syncModels := make([]messageModel, 0, len(models))
	for _, model := range models {
		if !model.OmitSync {
			syncModels = append(syncModels, model)
		}
	}

	g.P("struct CRUD {")
	for _, model := range models {
		g.P("\tlet ", swiftPropertyNameFromGoName(model.GoName), ": ", model.TableTypeName)
	}
	g.P("\tinit(_ q: any DBTX) {")
	for _, model := range models {
		g.P("\t\tself.", swiftPropertyNameFromGoName(model.GoName), " = ", model.TableTypeName, "(q)")
	}
	g.P("\t}")
	g.P()
	g.P("\tfunc tableDescriptors() -> [GeneratedTableDescriptor] {")
	g.P("\t\treturn [")
	for _, model := range models {
		g.P("\t\t\tGeneratedTableDescriptor(tableName: ", model.GoName, "TableName, typeName: ", model.GoName, "TypeName, isCore: false, syncEnabled: ", strconv.FormatBool(!model.OmitSync), "),")
	}
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableDeletedName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableSyncName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableSchemaStateName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableUnknownName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t]")
	g.P("\t}")
	g.P()
	g.P("\tprivate func dbtx() -> any DBTX {")
	g.P("\t\treturn ", swiftPropertyNameFromGoName(models[0].GoName), ".q")
	g.P("\t}")
	g.P()
	g.P("\tfunc initialize() throws {")
	for _, model := range models {
		g.P("\t\ttry ", swiftPropertyNameFromGoName(model.GoName), ".initialize()")
	}
	g.P("\t}")
	g.P()
	g.P("\tfunc writeJSONL(remote: String) throws -> String {")
	g.P("\t\tlet q = dbtx()")
	g.P("\t\tvar output = \"\"")
	for _, model := range syncModels {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		g.P("\t\tfor row in try ", propertyName, ".select() {")
		g.P("\t\t\tif !(try syncNeedsSend(q, objectID: row.id, tableName: ", model.GoName, "TableName, remote: remote, atNs: row.atNs)) {")
		g.P("\t\t\t\tcontinue")
		g.P("\t\t\t}")
		g.P("\t\t\tlet dataJSON = try marshalAnyJSON(row.data, typeName: ", model.GoName, "TypeName)")
		g.P("\t\t\toutput += try encodeJSONLRecord(JSONLRecord(id: row.id, deleted: false, atNs: row.atNs, data: dataJSON))")
		g.P("\t\t\ttry syncUpsert(q, objectID: row.id, tableName: ", model.GoName, "TableName, remote: remote, atNs: row.atNs)")
		g.P("\t\t}")
	}
	if len(syncModels) > 0 {
		args := make([]string, 0, len(syncModels))
		for _, model := range syncModels {
			args = append(args, model.GoName+"TableName")
		}
		placeholders := strings.TrimRight(strings.Repeat("?,", len(syncModels)), ",")
		g.P("\t\ttry q.withRows(\"SELECT table_name, id, at_ns FROM \\(_deletedTableName) WHERE table_name IN ("+placeholders+")\", arguments: [", strings.Join(args, ", "), "]) { rows in")
		g.P("\t\t\twhile let row = try rows.next() {")
		g.P("\t\t\t\tlet tableName = try row.string(at: 0)")
		g.P("\t\t\t\tlet id = try row.string(at: 1)")
		g.P("\t\t\t\tlet atNs = try row.int64(at: 2)")
		g.P("\t\t\t\tif !(try syncNeedsSend(q, objectID: id, tableName: tableName, remote: remote, atNs: atNs)) {")
		g.P("\t\t\t\t\tcontinue")
		g.P("\t\t\t\t}")
		g.P("\t\t\t\tlet typeName: String")
		g.P("\t\t\t\tswitch tableName {")
		for _, model := range syncModels {
			g.P("\t\t\t\tcase ", model.GoName, "TableName:")
			g.P("\t\t\t\t\ttypeName = ", model.GoName, "TypeName")
		}
		g.P("\t\t\t\tdefault:")
		g.P("\t\t\t\t\tthrow ProprDBError(\"unsupported tombstone table \\(tableName)\")")
		g.P("\t\t\t\t}")
		g.P("\t\t\t\tlet dataJSON = try marshalTypeOnlyAnyJSON(typeName: typeName)")
		g.P("\t\t\t\toutput += try encodeJSONLRecord(JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))")
		g.P("\t\t\t\ttry syncUpsert(q, objectID: id, tableName: tableName, remote: remote, atNs: atNs)")
		g.P("\t\t\t}")
		g.P("\t\t}")
	}
	g.P("\t\treturn output")
	g.P("\t}")
	g.P()
	g.P("\tfunc readJSONL(remote: String, text: String) throws {")
	g.P("\t\tlet q = dbtx()")
	g.P("\t\tvar readError: Error?")
	g.P("\t\tdo {")
	g.P("\t\t\ttry ", swiftRuntimeModuleName, ".readJSONL(text: text) { record, lineNumber in")
	g.P("\t\t\t\tif record.id.isEmpty {")
	g.P("\t\t\t\t\tthrow ProprDBError(\"jsonl line \\(lineNumber) has empty id\")")
	g.P("\t\t\t\t}")
	g.P("\t\t\t\tif record.data.isEmpty {")
	g.P("\t\t\t\t\tthrow ProprDBError(\"jsonl line \\(lineNumber) has empty data\")")
	g.P("\t\t\t\t}")
	g.P("\t\t\t\tlet typeName = try typeNameFromAnyJSON(record.data)")
	g.P("\t\t\t\tswitch typeName {")
	for _, model := range models {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		g.P("\t\t\t\tcase ", model.GoName, "TypeName:")
		if model.OmitSync {
			g.P("\t\t\t\t\tlogIgnoredUnsyncedJSONLRecord(typeName: typeName, id: record.id, remote: remote, lineNumber: lineNumber)")
			g.P("\t\t\t\t\treturn")
			continue
		}
		g.P("\t\t\t\t\tlet localMax = try localMaxAtNs(q, tableName: ", model.GoName, "TableName, objectID: record.id)")
		g.P("\t\t\t\t\ttry syncUpsert(q, objectID: record.id, tableName: ", model.GoName, "TableName, remote: remote, atNs: record.atNs)")
		g.P("\t\t\t\t\tif record.atNs < localMax {")
		g.P("\t\t\t\t\t\treturn")
		g.P("\t\t\t\t\t}")
		g.P("\t\t\t\t\tif record.deleted {")
		g.P("\t\t\t\t\t\ttry ", propertyName, ".tombstoneWithAtNs(id: record.id, atNs: record.atNs)")
		g.P("\t\t\t\t\t\treturn")
		g.P("\t\t\t\t\t}")
		g.P("\t\t\t\t\tlet data = try decodeAnyJSON(record.data, as: ", swiftMessageTypeName(file, model.GoName), ".self)")
		g.P("\t\t\t\t\ttry ", propertyName, ".upsertWithAtNs(id: record.id, atNs: record.atNs, data: data)")
		g.P("\t\t\t\t\treturn")
	}
	g.P("\t\t\t\tdefault:")
	g.P("\t\t\t\t\ttry unknownInsert(q, typeName: typeName, record: record)")
	g.P("\t\t\t\t}")
	g.P("\t\t\t}")
	g.P("\t\t} catch {")
	g.P("\t\t\treadError = error")
	g.P("\t\t}")
	g.P("\t\tdo {")
	g.P("\t\t\ttry compactUnknownLatest(q)")
	g.P("\t\t} catch {")
	g.P("\t\t\tif let readError {")
	g.P("\t\t\t\tthrow ProprDBError(\"read jsonl: \\(readError) (additionally, compact unknown rows: \\(error))\")")
	g.P("\t\t\t}")
	g.P("\t\t\tthrow error")
	g.P("\t\t}")
	g.P("\t\tif let readError {")
	g.P("\t\t\tthrow readError")
	g.P("\t\t}")
	g.P("\t}")
	g.P("}")
	g.P()
}

func swiftMessageTypeName(file *protogen.File, goName string) string {
	packageName := string(file.Desc.Package())
	if packageName == "" {
		return goName
	}
	parts := strings.Split(packageName, ".")
	swiftParts := make([]string, 0, len(parts)+1)
	for _, part := range parts {
		swiftParts = append(swiftParts, swiftTypeNameSegment(part))
	}
	swiftParts = append(swiftParts, goName)
	return strings.Join(swiftParts, "_")
}

func swiftTypeNameSegment(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(strings.ToLower(value))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func swiftPropertyNameFromGoName(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func escapeSwiftStringLiteralContent(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return replacer.Replace(value)
}
