package proprdbgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	swiftRuntimeModuleName = "ProprDBSwiftRuntime"
	swiftPublicVisibility  = "public"
)

type SwiftGeneratorOptions struct {
	Visibility           string
	PublicSynchronousAPI bool
}

type swiftEmitter struct {
	g               *protogen.GeneratedFile
	visibility      string
	actorVisibility string
}

// GenerateSwiftFile generates proprdb CRUD code for Swift.
func GenerateSwiftFile(plugin *protogen.Plugin, file *protogen.File, options SwiftGeneratorOptions) error {
	return GenerateSwiftFiles(plugin, []*protogen.File{file}, options)
}

func GenerateSwiftFiles(plugin *protogen.Plugin, files []*protogen.File, options SwiftGeneratorOptions) error {
	if len(files) == 0 {
		return nil
	}
	sort.Slice(files, func(left, right int) bool {
		return files[left].Desc.Path() < files[right].Desc.Path()
	})
	collector := modelCollector{}
	models := make([]messageModel, 0)
	modelFiles := make(map[string]*protogen.File)
	for _, file := range files {
		fileModels, err := collector.collectModels(file)
		if err != nil {
			return err
		}
		for _, model := range fileModels {
			modelFiles[model.TypeName] = file
		}
		models = append(models, fileModels...)
	}
	if len(models) == 0 {
		return nil
	}
	if err := validateModels(models); err != nil {
		return err
	}

	file := files[0]
	filename := file.GeneratedFilenamePrefix + ".proprdb.pb.swift"
	g := plugin.NewGeneratedFile(filename, "")
	g.P("// Code generated by protoc-gen-proprdb-swift. DO NOT EDIT.")
	g.P()
	g.P("import Foundation")
	g.P("import SwiftProtobuf")
	g.P("import ", swiftRuntimeModuleName)
	g.P()

	synchronousVisibility := ""
	if options.PublicSynchronousAPI {
		synchronousVisibility = swiftPublicVisibility
	}
	emitter := swiftEmitter{
		g:               g,
		visibility:      synchronousVisibility,
		actorVisibility: swiftVisibilityKeyword(options.Visibility),
	}
	for _, model := range models {
		emitter.emitModel(modelFiles[model.TypeName], model)
	}
	emitter.emitWrapper(modelFiles, models)
	_ = emitter.emitLegacyWrapper
	return nil
}

func (e swiftEmitter) emitModel(file *protogen.File, model messageModel) {
	g := e.g
	swiftTypeName := swiftMessageTypeName(file, model.GoName)
	tableNameConst := model.GoName + "TableName"
	typeNameConst := model.GoName + "TypeName"
	schemaConst := model.GoName + "ProjectionSchema"
	createTableConst := model.GoName + "CreateTableSQL"
	insertConst := model.GoName + "InsertSQL"
	upsertConst := model.GoName + "UpsertSQL"
	reprojectConst := model.GoName + "ReprojectSQL"
	indexPrefixConst := model.GoName + "GeneratedIndexPrefix"
	visibility := e.visibilityPrefix()
	sharedVisibility := e.sharedVisibilityPrefix()

	g.P(visibility, "let ", tableNameConst, " = ", strconv.Quote(model.TableName))
	g.P("private let ", tableNameConst, "Quoted = quoteSQLiteIdentifier(", tableNameConst, ")")
	g.P(visibility, "let ", typeNameConst, " = ", strconv.Quote(model.TypeName))
	g.P(visibility, "let ", schemaConst, " = ", strconv.Quote(model.ProjectionSchema))
	g.P("private let ", createTableConst, " = ", strconv.Quote(model.createTableSQL()))
	g.P("private let ", insertConst, " = ", strconv.Quote(model.insertSQL(false)))
	g.P("private let ", upsertConst, " = ", strconv.Quote(model.insertSQL(true)))
	g.P("private let ", indexPrefixConst, " = ", strconv.Quote(model.generatedIndexPrefix()))
	for indexPosition, indexModel := range model.Indexes {
		g.P("private let ", model.GoName, "CreateIndexSQL", strconv.Itoa(indexPosition+1), " = ", strconv.Quote(model.createIndexSQL(indexModel)))
	}
	if len(model.ProjectedFields) > 0 {
		g.P("private let ", reprojectConst, " = ", strconv.Quote(model.reprojectSQL()))
	}
	g.P()
	g.P("private let ", model.GoName, "GeneratedBinding = GeneratedTableBinding(")
	g.P("\tdescriptor: GeneratedTableDescriptor(tableName: ", tableNameConst, ", typeName: ", typeNameConst, ", isCore: false, syncEnabled: ", strconv.FormatBool(!model.OmitSync), ", changeListenersEnabled: ", strconv.FormatBool(model.ChangeListeners), ", queryStatisticsEnabled: ", strconv.FormatBool(model.QueryStatistics), "),")
	g.P("\tmessageType: ", swiftTypeName, ".self,")
	g.P("\tinsertSQL: ", insertConst, ",")
	g.P("\tupsertSQL: ", upsertConst, ",")
	g.P("\tdecodeAnyJSON: { try decodeAnyJSON($0, as: ", swiftTypeName, ".self) },")
	g.P("\tdecodeBinary: { try ", swiftTypeName, "(serializedBytes: $0) },")
	g.P("\tencodeAnyJSON: { message in")
	g.P("\t\tguard let data = message as? ", swiftTypeName, " else { throw ProprDBError(\"expected ", swiftTypeName, "\") }")
	g.P("\t\treturn try marshalAnyJSON(data, typeName: ", typeNameConst, ")")
	g.P("\t},")
	g.P("\tmessagesEqual: { left, right in")
	g.P("\t\tguard let left = left as? ", swiftTypeName, ", let right = right as? ", swiftTypeName, " else { return false }")
	g.P("\t\treturn left == right")
	g.P("\t},")
	g.P("\tprojectedValues: { message in")
	g.P("\t\tguard let data = message as? ", swiftTypeName, " else { throw ProprDBError(\"expected ", swiftTypeName, "\") }")
	g.P("\t\tvar values: [SQLiteBindValue] = []")
	for _, projectedField := range model.ProjectedFields {
		propertyName := swiftPropertyNameFromGoName(projectedField.GetterName[3:])
		if projectedField.IsOptional {
			presenceName := "has" + projectedField.GetterName[3:]
			g.P("\t\tif data.", presenceName, " { values.append(sqliteBindValue(data.", propertyName, ")) } else { values.append(.null) }")
		} else {
			g.P("\t\tvalues.append(sqliteBindValue(data.", propertyName, "))")
		}
	}
	g.P("\t\treturn values")
	g.P("\t}")
	g.P(")")
	g.P()

	g.P(sharedVisibility, "struct ", model.RowTypeName, ": Equatable, Sendable {")
	g.P("\t", sharedVisibility, "var id: String")
	g.P("\t", sharedVisibility, "var atNs: Int64")
	g.P("\t", sharedVisibility, "var data: ", swiftTypeName)
	g.P("\t", sharedVisibility, "init(id: String, atNs: Int64, data: ", swiftTypeName, ") {")
	g.P("\t\tself.id = id")
	g.P("\t\tself.atNs = atNs")
	g.P("\t\tself.data = data")
	g.P("\t}")
	g.P("}")
	g.P()
	if model.ChangeListeners {
		g.P(sharedVisibility, "typealias ", model.GoName, "Change = TableChange<", swiftTypeName, ">")
		g.P()
	}

	g.P(visibility, "struct ", model.TableTypeName, " {")
	g.P("\tfileprivate let q: any DBTX")
	g.P("\t", visibility, "init(_ q: any DBTX) {")
	g.P("\t\tself.q = q")
	g.P("\t}")
	g.P()

	e.emitSwiftInitMethod(file, model, swiftTypeName, tableNameConst, typeNameConst, schemaConst, createTableConst, indexPrefixConst)
	e.emitSwiftSelectMethod(model, swiftTypeName, tableNameConst)
	e.emitSwiftInsertMethod(model, swiftTypeName, tableNameConst, insertConst)
	e.emitSwiftUpdateMethod(model, swiftTypeName, tableNameConst, upsertConst)
	e.emitSwiftDeleteMethod(model)
	e.emitSwiftApplyWithAtNsMethods(model, swiftTypeName, tableNameConst, upsertConst)
	if len(model.ProjectedFields) > 0 {
		e.emitSwiftReprojectMethod(file, model, swiftTypeName, tableNameConst, reprojectConst)
	}
	e.emitSwiftDrainUnknownMethod(file, model, swiftTypeName, typeNameConst)
	if model.ChangeListeners {
		g.P("\t", visibility, "func changes() -> AsyncStream<", model.GoName, "Change> {")
		g.P("\t\ttableChanges(q, tableName: ", tableNameConst, ", as: ", swiftTypeName, ".self)")
		g.P("\t}")
		g.P()
	}
	g.P("}")
	g.P()
}

func (e swiftEmitter) emitSwiftInitMethod(file *protogen.File, model messageModel, swiftTypeName, tableNameConst, typeNameConst, schemaConst, createTableConst, indexPrefixConst string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func initialize() throws {")
	g.P("\t\ttry ensureCoreTables(q)")
	g.P("\t\ttry q.execute(", createTableConst, ")")
	if len(model.ProjectedFields) > 0 {
		g.P("\t\tlet existingColumns = try q.withRows(\"PRAGMA table_info(\\\"\\(", tableNameConst, ")\\\")\") { rows in")
		g.P("\t\t\tvar columns = Set<String>()")
		g.P("\t\t\twhile let row = try rows.next() {")
		g.P("\t\t\t\tcolumns.insert(try row.string(at: 1))")
		g.P("\t\t\t}")
		g.P("\t\t\treturn columns")
		g.P("\t\t}")
		for _, projectedField := range model.ProjectedFields {
			g.P("\t\tif !existingColumns.contains(", strconv.Quote(projectedField.ColumnName), ") {")
			g.P("\t\t\ttry q.execute(\"ALTER TABLE \" + ", tableNameConst, "Quoted + \" ADD COLUMN ", escapeSwiftStringLiteralContent(projectedField.createColumnSQL()), "\")")
			g.P("\t\t}")
		}
	}

	g.P("\t\ttry ensureManagedIndexes(q, tableName: ", tableNameConst, ", generatedIndexPrefix: ", indexPrefixConst, ", createIndexSQL: [")
	for indexPosition := range model.Indexes {
		g.P("\t\t\t", model.GoName, "CreateIndexSQL", strconv.Itoa(indexPosition+1), ",")
	}
	g.P("\t\t], desiredIndexNames: [")
	for _, indexModel := range model.Indexes {
		g.P("\t\t\t", strconv.Quote(indexModel.IndexName), ",")
	}
	g.P("\t\t])")

	g.P("\t\tlet currentSchema = try q.withRows(\"SELECT schema_hash FROM \\(_proprdbSchemaTableName) WHERE table_name = ?\", arguments: [", tableNameConst, "]) { rows -> String? in")
	g.P("\t\t\tif let row = try rows.next() {")
	g.P("\t\t\t\treturn try row.string(at: 0)")
	g.P("\t\t\t}")
	g.P("\t\t\treturn nil as String?")
	g.P("\t\t}")
	g.P("\t\tif let currentSchema, currentSchema != ", schemaConst, " {")
	if len(model.ProjectedFields) > 0 {
		g.P("\t\t\ttry reproject()")
	}
	g.P("\t\t\ttry q.execute(\"UPDATE \\(_proprdbSchemaTableName) SET schema_hash = ? WHERE table_name = ?\", arguments: [", schemaConst, ", ", tableNameConst, "])")
	g.P("\t\t} else if currentSchema == nil {")
	g.P("\t\t\ttry q.execute(\"INSERT INTO \\(_proprdbSchemaTableName) (table_name, schema_hash) VALUES (?, ?)\", arguments: [", tableNameConst, ", ", schemaConst, "])")
	g.P("\t\t}")
	g.P("\t\ttry drainUnknownRows(", typeNameConst, ")")
	g.P("\t}")
	g.P()
	_ = swiftTypeName
	_ = file
}

func (e swiftEmitter) emitSwiftSelectMethod(model messageModel, swiftTypeName, tableNameConst string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func select(where whereClause: String = \"\", arguments: [SQLiteBindValue] = []) throws -> [", model.RowTypeName, "] {")
	g.P("\t\tvar query = \"SELECT id, at_ns, data FROM \" + ", tableNameConst, "Quoted")
	g.P("\t\tif !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {")
	g.P("\t\t\tquery += \" WHERE \" + whereClause")
	g.P("\t\t}")
	if model.QueryStatistics {
		g.P("\t\treturn try measureQuery(q, tableName: ", tableNameConst, ", query: query) {")
	}
	g.P("\t\treturn try q.withRows(query, bindValues: arguments) { rows in")
	g.P("\t\t\tvar result: [", model.RowTypeName, "] = []")
	g.P("\t\t\twhile let row = try rows.next() {")
	g.P("\t\t\t\tlet id = try row.string(at: 0)")
	g.P("\t\t\t\tlet atNs = try row.int64(at: 1)")
	g.P("\t\t\t\tlet dataBytes = try row.data(at: 2)")
	g.P("\t\t\t\tlet data = try ", swiftTypeName, "(serializedBytes: dataBytes)")
	g.P("\t\t\t\tresult.append(", model.RowTypeName, "(id: id, atNs: atNs, data: data))")
	g.P("\t\t\t}")
	g.P("\t\t\treturn result")
	g.P("\t\t}")
	if model.QueryStatistics {
		g.P("\t\t}")
	}
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftInsertMethod(model messageModel, swiftTypeName, _, _ string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func insert(_ data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tlet id = try uuidV7()")
	g.P("\t\ttry validateUUID(id)")
	g.P("\t\treturn try insertWithIDInternal(id: id, data: data)")
	g.P("\t}")
	g.P()
	if model.AllowCustomIDInsert {
		g.P("\t", e.visibilityPrefix(), "func insertWithID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
		g.P("\t\treturn try insertWithIDInternal(id: id, data: data)")
		g.P("\t}")
		g.P()
	}
	g.P("\tprivate func insertWithIDInternal(id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry validateUUID(id)")
	if model.ValidateWrite {
		g.P("\t\ttry validateForWrite(data)")
	}
	g.P("\t\tlet atNs = try writeLocalObject(q, binding: ", model.GoName, "GeneratedBinding, id: id, message: data, insert: true)")
	g.P("\t\treturn ", model.RowTypeName, "(id: id, atNs: atNs, data: data)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftUpdateMethod(model messageModel, swiftTypeName, _, _ string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func updateByID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry validateUUID(id)")
	if model.ValidateWrite {
		g.P("\t\ttry validateForWrite(data)")
	}
	g.P("\t\tlet atNs = try writeLocalObject(q, binding: ", model.GoName, "GeneratedBinding, id: id, message: data, insert: false)")
	g.P("\t\treturn ", model.RowTypeName, "(id: id, atNs: atNs, data: data)")
	g.P("\t}")
	g.P()
	g.P("\t", e.visibilityPrefix(), "func updateRow(_ row: ", model.RowTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\treturn try updateByID(row.id, data: row.data)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftDeleteMethod(model messageModel) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func deleteByID(_ id: String) throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry deleteLocalObject(q, binding: ", model.GoName, "GeneratedBinding, id: id)")
	g.P("\t}")
	g.P()
	g.P("\t", e.visibilityPrefix(), "func deleteRow(_ row: ", model.RowTypeName, ") throws {")
	g.P("\t\ttry deleteByID(row.id)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftApplyWithAtNsMethods(model messageModel, swiftTypeName, _, _ string) {
	g := e.g
	g.P("\tfileprivate func upsertWithAtNs(id: String, atNs: Int64, data: ", swiftTypeName, ") throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\tlet dataJSON = try marshalAnyJSON(data, typeName: ", model.GoName, "TypeName)")
	g.P("\t\ttry applyIncomingObject(q, binding: ", model.GoName, "GeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))")
	g.P("\t}")
	g.P()
	g.P("\tfileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\tlet dataJSON = try marshalTypeOnlyAnyJSON(typeName: ", model.GoName, "TypeName)")
	g.P("\t\ttry applyIncomingObject(q, binding: ", model.GoName, "GeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftReprojectMethod(file *protogen.File, model messageModel, swiftTypeName, tableNameConst, reprojectConst string) {
	g := e.g
	g.P("\tprivate func reproject() throws {")
	g.P("\t\tlet rowsToReproject = try q.withRows(\"SELECT id, data FROM \" + ", tableNameConst, "Quoted) { rows in")
	g.P("\t\t\tvar buffered: [(String, Data)] = []")
	g.P("\t\t\twhile let row = try rows.next() {")
	g.P("\t\t\t\tbuffered.append((try row.string(at: 0), try row.data(at: 1)))")
	g.P("\t\t\t}")
	g.P("\t\t\treturn buffered")
	g.P("\t\t}")
	g.P("\t\tfor (id, dataBytes) in rowsToReproject {")
	g.P("\t\t\tlet data = try ", swiftTypeName, "(serializedBytes: dataBytes)")
	g.P("\t\t\tvar reprojectArguments: [Any?] = []")
	for _, projectedField := range model.ProjectedFields {
		e.emitSwiftProjectedFieldAppend("reprojectArguments", "data", projectedField, "\t\t\t")
	}
	g.P("\t\t\treprojectArguments.append(id)")
	g.P("\t\t\ttry q.execute(", reprojectConst, ", arguments: reprojectArguments)")
	g.P("\t\t}")
	g.P("\t}")
	g.P()
	_ = file
}

func (e swiftEmitter) emitSwiftDrainUnknownMethod(file *protogen.File, model messageModel, _, typeNameConst string) {
	g := e.g
	g.P("\tfileprivate func drainUnknownRows(_ typeName: String) throws {")
	g.P("\t\tguard typeName == ", typeNameConst, " else { throw ProprDBError(\"unexpected type name \\(typeName)\") }")
	g.P("\t\ttry drainBoundUnknown(q, bindings: [", model.GoName, "GeneratedBinding])")
	g.P("\t}")
	g.P()
	g.P("\t", e.visibilityPrefix(), "func drainUnknownRows() throws {")
	g.P("\t\ttry drainUnknownRows(", typeNameConst, ")")
	g.P("\t}")
	g.P()
	_ = file
}

func (e swiftEmitter) emitSwiftProjectedFieldAppend(argumentsName, dataName string, projectedField projectedField, indent string) {
	g := e.g
	propertyName := swiftPropertyNameFromGoName(projectedField.GetterName[3:])
	if !projectedField.IsOptional {
		g.P(indent, argumentsName, ".append(", dataName, ".", propertyName, ")")
		return
	}
	presenceName := "has" + projectedField.GetterName[3:]
	g.P(indent, "if ", dataName, ".", presenceName, " {")
	g.P(indent, "\t", argumentsName, ".append(", dataName, ".", propertyName, ")")
	g.P(indent, "} else {")
	g.P(indent, "\t", argumentsName, ".append(nil)")
	g.P(indent, "}")
}

func (e swiftEmitter) emitWrapper(modelFiles map[string]*protogen.File, models []messageModel) {
	g := e.g
	visibility := e.visibilityPrefix()
	actorVisibility := e.actorVisibilityPrefix()
	g.P("private let crudGeneratedBindings = [")
	for _, model := range models {
		g.P("\t", model.GoName, "GeneratedBinding,")
	}
	g.P("]")
	g.P()
	g.P(visibility, "struct CRUD {")
	for _, model := range models {
		g.P("\t", visibility, "let ", swiftPropertyNameFromGoName(model.GoName), ": ", model.TableTypeName)
	}
	g.P("\t", visibility, "init(_ q: any DBTX) {")
	if modelsHaveChangeListeners(models) {
		g.P("\t\tlet tracked = withChangeListeners(q)")
	}
	for _, model := range models {
		constructorQ := "q"
		if modelsHaveChangeListeners(models) {
			constructorQ = "tracked"
		}
		g.P("\t\tself.", swiftPropertyNameFromGoName(model.GoName), " = ", model.TableTypeName, "(", constructorQ, ")")
	}
	g.P("\t}")
	g.P("\tprivate func dbtx() -> any DBTX { ", swiftPropertyNameFromGoName(models[0].GoName), ".q }")
	g.P("\t", visibility, "func tableDescriptors() -> [GeneratedTableDescriptor] { crudGeneratedBindings.map(\\.descriptor) + coreTableDescriptors() }")
	g.P("\t", visibility, "func initialize() throws {")
	for _, model := range models {
		g.P("\t\ttry ", swiftPropertyNameFromGoName(model.GoName), ".initialize()")
	}
	g.P("\t}")
	g.P("\t", visibility, "func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try prepareBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote) }")
	g.P("\t", visibility, "func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try acknowledgeBoundJSONL(dbtx(), checkpoint: checkpoint) }")
	g.P("\t", visibility, "func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try discardBoundJSONL(dbtx(), checkpoint: checkpoint) }")
	g.P("\t", visibility, "func writeJSONL(remote: String) throws -> String {")
	g.P("\t\tlet prepared = try prepareJSONL(remote: remote)")
	g.P("\t\ttry acknowledgeJSONL(prepared.checkpoint)")
	g.P("\t\treturn prepared.text")
	g.P("\t}")
	g.P("\t", visibility, "func readJSONL(remote: String, text: String) throws { try readBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote, text: text) }")
	g.P("}")
	g.P()
	for _, model := range models {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		swiftTypeName := swiftMessageTypeName(modelFiles[model.TypeName], model.GoName)
		proxyName := model.GoName + "TableProxy"
		g.P(actorVisibility, "struct ", proxyName, ": Sendable {")
		g.P("\tfileprivate let actor: ProprDBActor")
		g.P()
		g.P("\t", actorVisibility, "func initialize() async throws { try await actor._", propertyName, "Initialize() }")
		g.P("\t", actorVisibility, "func select(where whereClause: String = \"\", arguments: [SQLiteBindValue] = []) async throws -> [", model.RowTypeName, "] { try await actor._", propertyName, "Select(where: whereClause, arguments: arguments) }")
		g.P("\t", actorVisibility, "func insert(_ data: ", swiftTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "Insert(data) }")
		if model.AllowCustomIDInsert {
			g.P("\t", actorVisibility, "func insertWithID(_ id: String, data: ", swiftTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "InsertWithID(id, data: data) }")
		}
		g.P("\t", actorVisibility, "func updateByID(_ id: String, data: ", swiftTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "UpdateByID(id, data: data) }")
		g.P("\t", actorVisibility, "func updateRow(_ row: ", model.RowTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "UpdateRow(row) }")
		g.P("\t", actorVisibility, "func deleteByID(_ id: String) async throws { try await actor._", propertyName, "DeleteByID(id) }")
		g.P("\t", actorVisibility, "func deleteRow(_ row: ", model.RowTypeName, ") async throws { try await actor._", propertyName, "DeleteRow(row) }")
		g.P("\t", actorVisibility, "func drainUnknownRows() async throws { try await actor._", propertyName, "DrainUnknownRows() }")
		if model.ChangeListeners {
			g.P("\t", actorVisibility, "func changes() async throws -> AsyncStream<", model.GoName, "Change> { try await actor._", propertyName, "Changes() }")
		}
		g.P("}")
		g.P()
	}
	g.P("extension ProprDBActor {")
	g.P("\t", actorVisibility, "func initialize() throws { try withDatabase { try CRUD($0).initialize() } }")
	g.P("\t", actorVisibility, "func tableDescriptors() throws -> [GeneratedTableDescriptor] { try withDatabase { CRUD($0).tableDescriptors() } }")
	for _, model := range models {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		swiftTypeName := swiftMessageTypeName(modelFiles[model.TypeName], model.GoName)
		proxyName := model.GoName + "TableProxy"
		g.P("\t", actorVisibility, "nonisolated var ", propertyName, ": ", proxyName, " { ", proxyName, "(actor: self) }")
		g.P("\tfileprivate func _", propertyName, "Initialize() throws { try withDatabase { try CRUD($0).", propertyName, ".initialize() } }")
		g.P("\tfileprivate func _", propertyName, "Select(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [", model.RowTypeName, "] { try withDatabase { try CRUD($0).", propertyName, ".select(where: whereClause, arguments: arguments) } }")
		g.P("\tfileprivate func _", propertyName, "Insert(_ data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".insert(data) } }")
		if model.AllowCustomIDInsert {
			g.P("\tfileprivate func _", propertyName, "InsertWithID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".insertWithID(id, data: data) } }")
		}
		g.P("\tfileprivate func _", propertyName, "UpdateByID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".updateByID(id, data: data) } }")
		g.P("\tfileprivate func _", propertyName, "UpdateRow(_ row: ", model.RowTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".updateRow(row) } }")
		g.P("\tfileprivate func _", propertyName, "DeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).", propertyName, ".deleteByID(id) } }")
		g.P("\tfileprivate func _", propertyName, "DeleteRow(_ row: ", model.RowTypeName, ") throws { try withDatabase { try CRUD($0).", propertyName, ".deleteRow(row) } }")
		g.P("\tfileprivate func _", propertyName, "DrainUnknownRows() throws { try withDatabase { try CRUD($0).", propertyName, ".drainUnknownRows() } }")
		if model.ChangeListeners {
			g.P("\tfileprivate func _", propertyName, "Changes() throws -> AsyncStream<", model.GoName, "Change> { try withDatabase { CRUD($0).", propertyName, ".changes() } }")
		}
	}
	g.P("\t", actorVisibility, "func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try withDatabase { try CRUD($0).prepareJSONL(remote: remote) } }")
	g.P("\t", actorVisibility, "func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).acknowledgeJSONL(checkpoint) } }")
	g.P("\t", actorVisibility, "func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).discardJSONL(checkpoint) } }")
	g.P("\t", actorVisibility, "func writeJSONL(remote: String) throws -> String { try withDatabase { try CRUD($0).writeJSONL(remote: remote) } }")
	g.P("\t", actorVisibility, "func readJSONL(remote: String, text: String) throws { try withDatabase { try CRUD($0).readJSONL(remote: remote, text: text) } }")
	g.P("}")
}

func (e swiftEmitter) emitLegacyWrapper(modelFiles map[string]*protogen.File, models []messageModel) {
	g := e.g
	syncModels := make([]messageModel, 0, len(models))
	for _, model := range models {
		if !model.OmitSync {
			syncModels = append(syncModels, model)
		}
	}

	visibility := e.visibilityPrefix()
	g.P(visibility, "struct CRUD {")
	for _, model := range models {
		g.P("\t", visibility, "let ", swiftPropertyNameFromGoName(model.GoName), ": ", model.TableTypeName)
	}
	g.P("\t", visibility, "init(_ q: any DBTX) {")
	for _, model := range models {
		g.P("\t\tself.", swiftPropertyNameFromGoName(model.GoName), " = ", model.TableTypeName, "(q)")
	}
	g.P("\t}")
	g.P()
	g.P("\t", visibility, "func tableDescriptors() -> [GeneratedTableDescriptor] {")
	g.P("\t\treturn [")
	for _, model := range models {
		g.P("\t\t\tGeneratedTableDescriptor(tableName: ", model.GoName, "TableName, typeName: ", model.GoName, "TypeName, isCore: false, syncEnabled: ", strconv.FormatBool(!model.OmitSync), "),")
	}
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableDeletedName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableSyncName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableSchemaStateName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t\tGeneratedTableDescriptor(tableName: coreTableUnknownName, typeName: \"\", isCore: true, syncEnabled: false),")
	g.P("\t\t]")
	g.P("\t}")
	g.P()
	g.P("\tprivate func dbtx() -> any DBTX {")
	g.P("\t\treturn ", swiftPropertyNameFromGoName(models[0].GoName), ".q")
	g.P("\t}")
	g.P()
	g.P("\t", visibility, "func initialize() throws {")
	for _, model := range models {
		g.P("\t\ttry ", swiftPropertyNameFromGoName(model.GoName), ".initialize()")
	}
	g.P("\t}")
	g.P()
	g.P("\t", visibility, "func writeJSONL(remote: String) throws -> String {")
	g.P("\t\tlet q = dbtx()")
	g.P("\t\tvar output = \"\"")
	for _, model := range syncModels {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		g.P("\t\tfor row in try ", propertyName, ".select() {")
		g.P("\t\t\tif !(try syncNeedsSend(q, objectID: row.id, tableName: ", model.GoName, "TableName, remote: remote, atNs: row.atNs)) {")
		g.P("\t\t\t\tcontinue")
		g.P("\t\t\t}")
		g.P("\t\t\tlet dataJSON = try marshalAnyJSON(row.data, typeName: ", model.GoName, "TypeName)")
		g.P("\t\t\toutput += try encodeJSONLRecord(JSONLRecord(id: row.id, deleted: false, atNs: row.atNs, data: dataJSON))")
		g.P("\t\t\ttry syncUpsert(q, objectID: row.id, tableName: ", model.GoName, "TableName, remote: remote, atNs: row.atNs)")
		g.P("\t\t}")
	}
	if len(syncModels) > 0 {
		args := make([]string, 0, len(syncModels))
		for _, model := range syncModels {
			args = append(args, model.GoName+"TableName")
		}
		placeholders := strings.TrimRight(strings.Repeat("?,", len(syncModels)), ",")
		g.P("\t\ttry q.withRows(\"SELECT table_name, id, at_ns FROM \\(_deletedTableName) WHERE table_name IN ("+placeholders+")\", arguments: [", strings.Join(args, ", "), "]) { rows in")
		g.P("\t\t\twhile let row = try rows.next() {")
		g.P("\t\t\t\tlet tableName = try row.string(at: 0)")
		g.P("\t\t\t\tlet id = try row.string(at: 1)")
		g.P("\t\t\t\tlet atNs = try row.int64(at: 2)")
		g.P("\t\t\t\tif !(try syncNeedsSend(q, objectID: id, tableName: tableName, remote: remote, atNs: atNs)) {")
		g.P("\t\t\t\t\tcontinue")
		g.P("\t\t\t\t}")
		g.P("\t\t\t\tlet typeName: String")
		g.P("\t\t\t\tswitch tableName {")
		for _, model := range syncModels {
			g.P("\t\t\t\tcase ", model.GoName, "TableName:")
			g.P("\t\t\t\t\ttypeName = ", model.GoName, "TypeName")
		}
		g.P("\t\t\t\tdefault:")
		g.P("\t\t\t\t\tthrow ProprDBError(\"unsupported tombstone table \\(tableName)\")")
		g.P("\t\t\t\t}")
		g.P("\t\t\t\tlet dataJSON = try marshalTypeOnlyAnyJSON(typeName: typeName)")
		g.P("\t\t\t\toutput += try encodeJSONLRecord(JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))")
		g.P("\t\t\t\ttry syncUpsert(q, objectID: id, tableName: tableName, remote: remote, atNs: atNs)")
		g.P("\t\t\t}")
		g.P("\t\t}")
	}
	g.P("\t\treturn output")
	g.P("\t}")
	g.P()
	g.P("\t", visibility, "func readJSONL(remote: String, text: String) throws {")
	g.P("\t\tlet q = dbtx()")
	g.P("\t\tvar readError: Error?")
	g.P("\t\tdo {")
	g.P("\t\t\ttry ", swiftRuntimeModuleName, ".readJSONL(text: text) { record, lineNumber in")
	g.P("\t\t\t\tif record.id.isEmpty {")
	g.P("\t\t\t\t\tthrow ProprDBError(\"jsonl line \\(lineNumber) has empty id\")")
	g.P("\t\t\t\t}")
	g.P("\t\t\t\tif record.data.isEmpty {")
	g.P("\t\t\t\t\tthrow ProprDBError(\"jsonl line \\(lineNumber) has empty data\")")
	g.P("\t\t\t\t}")
	g.P("\t\t\t\tlet typeName = try typeNameFromAnyJSON(record.data)")
	g.P("\t\t\t\tswitch typeName {")
	for _, model := range models {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		g.P("\t\t\t\tcase ", model.GoName, "TypeName:")
		if model.OmitSync {
			g.P("\t\t\t\t\tlogIgnoredUnsyncedJSONLRecord(typeName: typeName, id: record.id, remote: remote, lineNumber: lineNumber)")
			g.P("\t\t\t\t\treturn")
			continue
		}
		g.P("\t\t\t\t\tlet localMax = try localMaxAtNs(q, tableName: ", model.GoName, "TableName, objectID: record.id)")
		g.P("\t\t\t\t\ttry syncUpsert(q, objectID: record.id, tableName: ", model.GoName, "TableName, remote: remote, atNs: record.atNs)")
		g.P("\t\t\t\t\tif record.atNs < localMax {")
		g.P("\t\t\t\t\t\treturn")
		g.P("\t\t\t\t\t}")
		g.P("\t\t\t\t\tif record.deleted {")
		g.P("\t\t\t\t\t\ttry ", propertyName, ".tombstoneWithAtNs(id: record.id, atNs: record.atNs)")
		g.P("\t\t\t\t\t\treturn")
		g.P("\t\t\t\t\t}")
		g.P("\t\t\t\t\tlet data = try decodeAnyJSON(record.data, as: ", swiftMessageTypeName(modelFiles[model.TypeName], model.GoName), ".self)")
		g.P("\t\t\t\t\ttry ", propertyName, ".upsertWithAtNs(id: record.id, atNs: record.atNs, data: data)")
		g.P("\t\t\t\t\treturn")
	}
	g.P("\t\t\t\tdefault:")
	g.P("\t\t\t\t\ttry unknownInsert(q, typeName: typeName, record: record)")
	g.P("\t\t\t\t}")
	g.P("\t\t\t}")
	g.P("\t\t} catch {")
	g.P("\t\t\treadError = error")
	g.P("\t\t}")
	g.P("\t\tdo {")
	g.P("\t\t\ttry compactUnknownLatest(q)")
	g.P("\t\t} catch {")
	g.P("\t\t\tif let readError {")
	g.P("\t\t\t\tthrow ProprDBError(\"read jsonl: \\(readError) (additionally, compact unknown rows: \\(error))\")")
	g.P("\t\t\t}")
	g.P("\t\t\tthrow error")
	g.P("\t\t}")
	g.P("\t\tif let readError {")
	g.P("\t\t\tthrow readError")
	g.P("\t\t}")
	g.P("\t}")
	g.P("}")
	g.P()
	g.P(visibility, "extension ProprDBActor {")
	g.P("\t", visibility, "func initialize() throws {")
	g.P("\t\ttry withDatabase { database in try CRUD(database).initialize() }")
	g.P("\t}")
	for _, model := range models {
		propertyName := swiftPropertyNameFromGoName(model.GoName)
		swiftTypeName := swiftMessageTypeName(modelFiles[model.TypeName], model.GoName)
		g.P()
		g.P("\t", visibility, "func select", model.GoName, "() throws -> [", model.RowTypeName, "] {")
		g.P("\t\ttry withDatabase { database in try ", model.TableTypeName, "(database).select() }")
		g.P("\t}")
		g.P()
		g.P("\t", visibility, "func insert", model.GoName, "(_ data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
		g.P("\t\ttry withDatabase { database in try ", model.TableTypeName, "(database).insert(data) }")
		g.P("\t}")
		g.P()
		g.P("\t", visibility, "func update", model.GoName, "ByID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
		g.P("\t\ttry withDatabase { database in try ", model.TableTypeName, "(database).updateByID(id, data: data) }")
		g.P("\t}")
		g.P()
		g.P("\t", visibility, "func delete", model.GoName, "ByID(_ id: String) throws {")
		g.P("\t\ttry withDatabase { database in try ", model.TableTypeName, "(database).deleteByID(id) }")
		g.P("\t}")
		_ = propertyName
	}
	g.P()
	g.P("\t", visibility, "func writeJSONL(remote: String) throws -> String {")
	g.P("\t\ttry withDatabase { database in try CRUD(database).writeJSONL(remote: remote) }")
	g.P("\t}")
	g.P()
	g.P("\t", visibility, "func readJSONL(remote: String, text: String) throws {")
	g.P("\t\ttry withDatabase { database in try CRUD(database).readJSONL(remote: remote, text: text) }")
	g.P("\t}")
	g.P("}")
}

func swiftMessageTypeName(file *protogen.File, goName string) string {
	packageName := string(file.Desc.Package())
	if packageName == "" {
		return goName
	}
	parts := strings.Split(packageName, ".")
	swiftParts := make([]string, 0, len(parts)+1)
	for _, part := range parts {
		swiftParts = append(swiftParts, swiftTypeNameSegment(part))
	}
	swiftParts = append(swiftParts, goName)
	return strings.Join(swiftParts, "_")
}

func swiftTypeNameSegment(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(strings.ToLower(value))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func swiftPropertyNameFromGoName(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func escapeSwiftStringLiteralContent(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return replacer.Replace(value)
}

func (e swiftEmitter) visibilityPrefix() string {
	if e.visibility == "" {
		return ""
	}
	return e.visibility + " "
}

func (e swiftEmitter) actorVisibilityPrefix() string {
	if e.actorVisibility == "" {
		return ""
	}
	return e.actorVisibility + " "
}

func (e swiftEmitter) sharedVisibilityPrefix() string {
	if e.visibility == swiftPublicVisibility || e.actorVisibility == swiftPublicVisibility {
		return swiftPublicVisibility + " "
	}
	if e.visibility != "" {
		return e.visibility + " "
	}
	return e.actorVisibilityPrefix()
}

func ParseSwiftGeneratorOptions(rawOptions map[string]string) (SwiftGeneratorOptions, error) {
	options := SwiftGeneratorOptions{Visibility: "Public"}
	for name, value := range rawOptions {
		switch name {
		case "Visibility":
			if err := validateSwiftVisibility(value); err != nil {
				return SwiftGeneratorOptions{}, err
			}
			options.Visibility = value
		case "PublicSynchronousAPI":
			publicSynchronousAPI, err := strconv.ParseBool(value)
			if err != nil {
				return SwiftGeneratorOptions{}, fmt.Errorf("parse PublicSynchronousAPI: %w", err)
			}
			options.PublicSynchronousAPI = publicSynchronousAPI
		default:
			return SwiftGeneratorOptions{}, fmt.Errorf("unsupported option %q", name)
		}
	}
	return options, nil
}

func validateSwiftVisibility(value string) error {
	switch value {
	case "Public", "Internal", "Package":
		return nil
	default:
		return fmt.Errorf("unsupported Visibility %q", value)
	}
}

func swiftVisibilityKeyword(value string) string {
	switch value {
	case "Public":
		return swiftPublicVisibility
	case "Internal":
		return "internal"
	case "Package":
		return "package"
	default:
		return ""
	}
}
