package proprdbgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	swiftRuntimeModuleName = "ProprDBSwiftRuntime"
	swiftPublicVisibility  = "public"
)

type SwiftGeneratorOptions struct {
	Visibility           string
	PublicSynchronousAPI bool
}

type swiftEmitter struct {
	g               *protogen.GeneratedFile
	visibility      string
	actorVisibility string
}

// GenerateSwiftFile generates proprdb CRUD code for Swift.
func GenerateSwiftFile(plugin *protogen.Plugin, file *protogen.File, options SwiftGeneratorOptions) error {
	return GenerateSwiftFiles(plugin, []*protogen.File{file}, options)
}

func GenerateSwiftFiles(plugin *protogen.Plugin, files []*protogen.File, options SwiftGeneratorOptions) error {
	if len(files) == 0 {
		return nil
	}
	sort.Slice(files, func(left, right int) bool {
		return files[left].Desc.Path() < files[right].Desc.Path()
	})
	collector := modelCollector{}
	models := make([]messageModel, 0)
	modelFiles := make(map[string]*protogen.File)
	for _, file := range files {
		fileModels, err := collector.collectModels(file)
		if err != nil {
			return err
		}
		for _, model := range fileModels {
			modelFiles[model.TypeName] = file
		}
		models = append(models, fileModels...)
	}
	if len(models) == 0 {
		return nil
	}
	if err := validateModels(models); err != nil {
		return err
	}

	file := files[0]
	filename := file.GeneratedFilenamePrefix + ".proprdb.pb.swift"
	g := plugin.NewGeneratedFile(filename, "")
	g.P("// Code generated by protoc-gen-proprdb-swift. DO NOT EDIT.")
	g.P()
	g.P("import Foundation")
	g.P("import SwiftProtobuf")
	g.P("import ", swiftRuntimeModuleName)
	g.P()

	synchronousVisibility := ""
	if options.PublicSynchronousAPI {
		synchronousVisibility = swiftPublicVisibility
	}
	emitter := swiftEmitter{
		g:               g,
		visibility:      synchronousVisibility,
		actorVisibility: swiftVisibilityKeyword(options.Visibility),
	}
	for _, model := range models {
		emitter.emitModel(modelFiles[model.TypeName], model)
	}
	emitter.emitWrapper(modelFiles, models)
	return nil
}

func (e swiftEmitter) emitModel(file *protogen.File, model messageModel) {
	g := e.g
	swiftTypeName := model.SwiftTypeName
	tableNameConst := model.GoName + "TableName"
	typeNameConst := model.GoName + "TypeName"
	schemaConst := model.GoName + "ProjectionSchema"
	createTableConst := model.GoName + "CreateTableSQL"
	insertConst := model.GoName + "InsertSQL"
	upsertConst := model.GoName + "UpsertSQL"
	indexPrefixConst := model.GoName + "GeneratedIndexPrefix"
	visibility := e.visibilityPrefix()
	sharedVisibility := e.sharedVisibilityPrefix()

	g.P(visibility, "let ", tableNameConst, " = ", strconv.Quote(model.TableName))
	g.P("private let ", tableNameConst, "Quoted = quoteSQLiteIdentifier(", tableNameConst, ")")
	g.P(visibility, "let ", typeNameConst, " = ", strconv.Quote(model.TypeName))
	g.P(visibility, "let ", schemaConst, " = ", strconv.Quote(model.ProjectionSchema))
	g.P("private let ", createTableConst, " = ", strconv.Quote(model.createTableSQL()))
	g.P("private let ", insertConst, " = ", strconv.Quote(model.insertSQL(false)))
	g.P("private let ", upsertConst, " = ", strconv.Quote(model.insertSQL(true)))
	g.P("private let ", indexPrefixConst, " = ", strconv.Quote(model.generatedIndexPrefix()))
	for indexPosition, indexModel := range model.Indexes {
		g.P("private let ", model.GoName, "CreateIndexSQL", strconv.Itoa(indexPosition+1), " = ", strconv.Quote(model.createIndexSQL(indexModel)))
	}
	g.P()
	g.P("private let ", model.GoName, "GeneratedBinding = GeneratedTableBinding(")
	g.P("\tdescriptor: GeneratedTableDescriptor(tableName: ", tableNameConst, ", typeName: ", typeNameConst, ", isCore: false, syncEnabled: ", strconv.FormatBool(!model.OmitSync), ", changeListenersEnabled: ", strconv.FormatBool(model.ChangeListeners), ", queryStatisticsEnabled: ", strconv.FormatBool(model.QueryStatistics), "),")
	g.P("\tmessageType: ", swiftTypeName, ".self,")
	g.P("\tinsertSQL: ", insertConst, ",")
	g.P("\tupsertSQL: ", upsertConst, ",")
	g.P("\tcreateTableSQL: ", createTableConst, ",")
	g.P("\tprojectionSchema: ", schemaConst, ",")
	g.P("\tprojectedColumns: [")
	for _, projectedField := range model.ProjectedFields {
		protoKind := strings.TrimPrefix(strings.TrimSuffix(projectedField.SchemaSignature, projectionOptionalFlag), projectedField.ColumnName+":")
		g.P("\t\tProjectedColumnDescriptor(name: ", strconv.Quote(projectedField.ColumnName), ", protoKind: ", strconv.Quote(protoKind), ", sqliteType: ", strconv.Quote(projectedField.SQLiteType), ", defaultSQL: ", strconv.Quote(projectedField.SQLiteDefault), ", nullable: ", strconv.FormatBool(projectedField.IsOptional), ", legacyOneofPresenceRepair: ", strconv.FormatBool(projectedField.LegacyOneofPresenceRepair), "),")
	}
	g.P("\t],")
	g.P("\tgeneratedIndexes: [")
	for indexPosition, indexModel := range model.Indexes {
		g.P("\t\tGeneratedIndexDescriptor(name: ", strconv.Quote(indexModel.IndexName), ", createSQL: ", model.GoName, "CreateIndexSQL", strconv.Itoa(indexPosition+1), "),")
	}
	g.P("\t],")
	g.P("\tgeneratedIndexPrefix: ", indexPrefixConst, ",")
	g.P("\tdecodeAnyJSON: { try decodeAnyJSON($0, as: ", swiftTypeName, ".self) },")
	g.P("\tdecodeBinary: { try ", swiftTypeName, "(serializedBytes: $0) },")
	g.P("\tencodeAnyJSON: { message in")
	g.P("\t\tguard let data = message as? ", swiftTypeName, " else { throw ProprDBError(\"expected ", swiftTypeName, "\") }")
	g.P("\t\treturn try marshalAnyJSON(data, typeName: ", typeNameConst, ")")
	g.P("\t},")
	g.P("\tmessagesEqual: { left, right in")
	g.P("\t\tguard let left = left as? ", swiftTypeName, ", let right = right as? ", swiftTypeName, " else { return false }")
	g.P("\t\treturn left == right")
	g.P("\t},")
	g.P("\tprojectedValues: { message in")
	g.P("\t\tguard let data = message as? ", swiftTypeName, " else { throw ProprDBError(\"expected ", swiftTypeName, "\") }")
	g.P("\t\tvar values: [SQLiteBindValue] = []")
	for _, projectedField := range model.ProjectedFields {
		propertyName := projectedField.SwiftPropertyName
		if projectedField.IsOptional {
			if projectedField.LegacyOneofPresenceRepair {
				g.P("\t\tif case .", propertyName, " = data.", projectedField.SwiftOneofPropertyName, " { values.append(sqliteBindValue(data.", propertyName, ")) } else { values.append(.null) }")
			} else {
				g.P("\t\tif data.", projectedField.SwiftPresenceName, " { values.append(sqliteBindValue(data.", propertyName, ")) } else { values.append(.null) }")
			}
		} else {
			g.P("\t\tvalues.append(sqliteBindValue(data.", propertyName, "))")
		}
	}
	g.P("\t\treturn values")
	g.P("\t}")
	g.P(")")
	g.P()

	g.P(sharedVisibility, "struct ", model.RowTypeName, ": Equatable, Sendable {")
	g.P("\t", sharedVisibility, "var id: String")
	g.P("\t", sharedVisibility, "var atNs: Int64")
	g.P("\t", sharedVisibility, "var data: ", swiftTypeName)
	g.P("\t", sharedVisibility, "init(id: String, atNs: Int64, data: ", swiftTypeName, ") {")
	g.P("\t\tself.id = id")
	g.P("\t\tself.atNs = atNs")
	g.P("\t\tself.data = data")
	g.P("\t}")
	g.P("}")
	g.P()
	if model.ChangeListeners {
		g.P(sharedVisibility, "typealias ", model.GoName, "Change = TableChange<", swiftTypeName, ">")
		g.P()
	}

	g.P(visibility, "struct ", model.TableTypeName, " {")
	g.P("\tfileprivate let q: any DBTX")
	g.P("\t", visibility, "init(_ q: any DBTX) {")
	if model.ChangeListeners {
		g.P("\t\tself.q = withChangeListeners(q)")
	} else {
		g.P("\t\tself.q = q")
	}
	g.P("\t}")
	g.P()

	e.emitSwiftInitMethod(file, model, swiftTypeName, tableNameConst, typeNameConst, schemaConst, createTableConst, indexPrefixConst)
	e.emitSwiftSelectMethod(model, swiftTypeName, tableNameConst)
	e.emitSwiftInsertMethod(model, swiftTypeName, tableNameConst, insertConst)
	e.emitSwiftUpdateMethod(model, swiftTypeName, tableNameConst, upsertConst)
	e.emitSwiftDeleteMethod(model)
	e.emitSwiftApplyWithAtNsMethods(model, swiftTypeName, tableNameConst, upsertConst)
	e.emitSwiftDrainUnknownMethod(file, model, swiftTypeName, typeNameConst)
	if model.ChangeListeners {
		g.P("\t", visibility, "func changes() -> AsyncStream<", model.GoName, "Change> {")
		g.P("\t\ttableChanges(q, tableName: ", tableNameConst, ", as: ", swiftTypeName, ".self)")
		g.P("\t}")
		g.P()
	}
	g.P("}")
	g.P()
}

func (e swiftEmitter) emitSwiftInitMethod(file *protogen.File, model messageModel, swiftTypeName, _, typeNameConst, schemaConst, createTableConst, indexPrefixConst string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func initialize() throws {")
	g.P("\t\ttry ensureCoreTables(q)")
	g.P("\t\ttry auditObjectIDs(q, bindings: [", model.GoName, "GeneratedBinding])")
	g.P("\t\ttry reconcileGeneratedTable(q, binding: ", model.GoName, "GeneratedBinding)")
	g.P("\t\ttry drainUnknownRows(", typeNameConst, ")")
	g.P("\t}")
	g.P()
	_ = swiftTypeName
	_ = file
	_ = schemaConst
	_ = createTableConst
	_ = indexPrefixConst
}

func (e swiftEmitter) emitSwiftSelectMethod(model messageModel, swiftTypeName, tableNameConst string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func select(where whereClause: String = \"\", arguments: [SQLiteBindValue] = []) throws -> [", model.RowTypeName, "] {")
	g.P("\t\tvar query = \"SELECT id, at_ns, data FROM \" + ", tableNameConst, "Quoted")
	g.P("\t\tif !whereClause.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {")
	g.P("\t\t\tquery += \" WHERE \" + whereClause")
	g.P("\t\t}")
	if model.QueryStatistics {
		g.P("\t\treturn try measureQuery(q, tableName: ", tableNameConst, ", query: query) {")
	}
	g.P("\t\treturn try q.withRows(query, bindValues: arguments) { rows in")
	g.P("\t\t\tvar result: [", model.RowTypeName, "] = []")
	g.P("\t\t\twhile let row = try rows.next() {")
	g.P("\t\t\t\tlet id = try row.string(at: 0)")
	g.P("\t\t\t\tlet atNs = try row.int64(at: 1)")
	g.P("\t\t\t\tlet dataBytes = try row.data(at: 2)")
	g.P("\t\t\t\tlet data = try ", swiftTypeName, "(serializedBytes: dataBytes)")
	g.P("\t\t\t\tresult.append(", model.RowTypeName, "(id: id, atNs: atNs, data: data))")
	g.P("\t\t\t}")
	g.P("\t\t\treturn result")
	g.P("\t\t}")
	if model.QueryStatistics {
		g.P("\t\t}")
	}
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftInsertMethod(model messageModel, swiftTypeName, _, _ string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func insert(_ data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tlet id = try uuidV7()")
	g.P("\t\ttry validateUUIDV7(id)")
	g.P("\t\treturn try insertWithIDInternal(id: id, data: data)")
	g.P("\t}")
	g.P()
	if model.AllowCustomIDInsert {
		g.P("\t", e.visibilityPrefix(), "func insertWithID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
		g.P("\t\treturn try insertWithIDInternal(id: id, data: data)")
		g.P("\t}")
		g.P()
	}
	g.P("\tprivate func insertWithIDInternal(id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry validateUUIDV7(id)")
	if model.ValidateWrite {
		g.P("\t\ttry validateForWrite(data)")
	}
	g.P("\t\tlet atNs = try writeLocalObject(q, binding: ", model.GoName, "GeneratedBinding, id: id, message: data, insert: true)")
	g.P("\t\treturn ", model.RowTypeName, "(id: id, atNs: atNs, data: data)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftUpdateMethod(model messageModel, swiftTypeName, _, _ string) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func updateByID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry validateUUIDV7(id)")
	if model.ValidateWrite {
		g.P("\t\ttry validateForWrite(data)")
	}
	g.P("\t\tlet atNs = try writeLocalObject(q, binding: ", model.GoName, "GeneratedBinding, id: id, message: data, insert: false)")
	g.P("\t\treturn ", model.RowTypeName, "(id: id, atNs: atNs, data: data)")
	g.P("\t}")
	g.P()
	g.P("\t", e.visibilityPrefix(), "func updateRow(_ row: ", model.RowTypeName, ") throws -> ", model.RowTypeName, " {")
	g.P("\t\treturn try updateByID(row.id, data: row.data)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftDeleteMethod(model messageModel) {
	g := e.g
	g.P("\t", e.visibilityPrefix(), "func deleteByID(_ id: String) throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\ttry deleteLocalObject(q, binding: ", model.GoName, "GeneratedBinding, id: id)")
	g.P("\t}")
	g.P()
	g.P("\t", e.visibilityPrefix(), "func deleteRow(_ row: ", model.RowTypeName, ") throws {")
	g.P("\t\ttry deleteByID(row.id)")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftApplyWithAtNsMethods(model messageModel, swiftTypeName, _, _ string) {
	g := e.g
	g.P("\tfileprivate func upsertWithAtNs(id: String, atNs: Int64, data: ", swiftTypeName, ") throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\tlet dataJSON = try marshalAnyJSON(data, typeName: ", model.GoName, "TypeName)")
	g.P("\t\ttry applyIncomingObject(q, binding: ", model.GoName, "GeneratedBinding, record: JSONLRecord(id: id, deleted: false, atNs: atNs, data: dataJSON))")
	g.P("\t}")
	g.P()
	g.P("\tfileprivate func tombstoneWithAtNs(id: String, atNs: Int64) throws {")
	g.P("\t\tif id.isEmpty {")
	g.P("\t\t\tthrow ProprDBError(\"empty id\")")
	g.P("\t\t}")
	g.P("\t\tlet dataJSON = try marshalTypeOnlyAnyJSON(typeName: ", model.GoName, "TypeName)")
	g.P("\t\ttry applyIncomingObject(q, binding: ", model.GoName, "GeneratedBinding, record: JSONLRecord(id: id, deleted: true, atNs: atNs, data: dataJSON))")
	g.P("\t}")
	g.P()
}

func (e swiftEmitter) emitSwiftDrainUnknownMethod(file *protogen.File, model messageModel, _, typeNameConst string) {
	g := e.g
	g.P("\tfileprivate func drainUnknownRows(_ typeName: String) throws {")
	g.P("\t\tguard typeName == ", typeNameConst, " else { throw ProprDBError(\"unexpected type name \\(typeName)\") }")
	g.P("\t\ttry drainBoundUnknown(q, bindings: [", model.GoName, "GeneratedBinding])")
	g.P("\t}")
	g.P()
	g.P("\t", e.visibilityPrefix(), "func drainUnknownRows() throws {")
	g.P("\t\ttry drainUnknownRows(", typeNameConst, ")")
	g.P("\t}")
	g.P()
	_ = file
}

func (e swiftEmitter) emitWrapper(_ map[string]*protogen.File, models []messageModel) {
	g := e.g
	visibility := e.visibilityPrefix()
	actorVisibility := e.actorVisibilityPrefix()
	g.P("private let crudGeneratedBindings = [")
	for _, model := range models {
		g.P("\t", model.GoName, "GeneratedBinding,")
	}
	g.P("]")
	g.P()
	g.P(visibility, "struct CRUD {")
	for _, model := range models {
		g.P("\t", visibility, "let ", model.SwiftPropertyName, ": ", model.TableTypeName)
	}
	g.P("\t", visibility, "init(_ q: any DBTX) {")
	if modelsHaveChangeListeners(models) {
		g.P("\t\tlet tracked = withChangeListeners(q)")
	}
	for _, model := range models {
		constructorQ := "q"
		if modelsHaveChangeListeners(models) {
			constructorQ = "tracked"
		}
		g.P("\t\tself.", model.SwiftPropertyName, " = ", model.TableTypeName, "(", constructorQ, ")")
	}
	g.P("\t}")
	g.P("\tprivate func dbtx() -> any DBTX { ", models[0].SwiftPropertyName, ".q }")
	g.P("\t", visibility, "func tableDescriptors() -> [GeneratedTableDescriptor] { crudGeneratedBindings.map(\\.descriptor) + coreTableDescriptors() }")
	g.P("\t", visibility, "func initialize() throws {")
	for _, model := range models {
		g.P("\t\ttry ", model.SwiftPropertyName, ".initialize()")
	}
	g.P("\t}")
	g.P("\t", visibility, "func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try prepareBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote) }")
	g.P("\t", visibility, "func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try acknowledgeBoundJSONL(dbtx(), checkpoint: checkpoint) }")
	g.P("\t", visibility, "func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try discardBoundJSONL(dbtx(), checkpoint: checkpoint) }")
	g.P("\t", visibility, "func writeJSONL(remote: String) throws -> String {")
	g.P("\t\tlet prepared = try prepareJSONL(remote: remote)")
	g.P("\t\ttry acknowledgeJSONL(prepared.checkpoint)")
	g.P("\t\treturn prepared.text")
	g.P("\t}")
	g.P("\t", visibility, "func readJSONL(remote: String, stream: InputStream) throws { try readBoundJSONL(dbtx(), bindings: crudGeneratedBindings, remote: remote, stream: stream) }")
	g.P("}")
	g.P()
	for _, model := range models {
		propertyName := model.SwiftPropertyName
		swiftTypeName := model.SwiftTypeName
		proxyName := model.GoName + "TableProxy"
		g.P(actorVisibility, "struct ", proxyName, ": Sendable {")
		g.P("\tfileprivate let actor: ProprDBActor")
		g.P()
		g.P("\t", actorVisibility, "func initialize() async throws { try await actor._", propertyName, "Initialize() }")
		g.P("\t", actorVisibility, "func select(where whereClause: String = \"\", arguments: [SQLiteBindValue] = []) async throws -> [", model.RowTypeName, "] { try await actor._", propertyName, "Select(where: whereClause, arguments: arguments) }")
		g.P("\t", actorVisibility, "func insert(_ data: ", swiftTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "Insert(data) }")
		if model.AllowCustomIDInsert {
			g.P("\t", actorVisibility, "func insertWithID(_ id: String, data: ", swiftTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "InsertWithID(id, data: data) }")
		}
		g.P("\t", actorVisibility, "func updateByID(_ id: String, data: ", swiftTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "UpdateByID(id, data: data) }")
		g.P("\t", actorVisibility, "func updateRow(_ row: ", model.RowTypeName, ") async throws -> ", model.RowTypeName, " { try await actor._", propertyName, "UpdateRow(row) }")
		g.P("\t", actorVisibility, "func deleteByID(_ id: String) async throws { try await actor._", propertyName, "DeleteByID(id) }")
		g.P("\t", actorVisibility, "func deleteRow(_ row: ", model.RowTypeName, ") async throws { try await actor._", propertyName, "DeleteRow(row) }")
		g.P("\t", actorVisibility, "func drainUnknownRows() async throws { try await actor._", propertyName, "DrainUnknownRows() }")
		if model.ChangeListeners {
			g.P("\t", actorVisibility, "func changes() async throws -> AsyncStream<", model.GoName, "Change> { try await actor._", propertyName, "Changes() }")
		}
		g.P("}")
		g.P()
	}
	g.P("extension ProprDBActor {")
	g.P("\t", actorVisibility, "func initialize() throws { try withDatabase { try CRUD($0).initialize() } }")
	g.P("\t", actorVisibility, "func tableDescriptors() throws -> [GeneratedTableDescriptor] { try withDatabase { CRUD($0).tableDescriptors() } }")
	for _, model := range models {
		propertyName := model.SwiftPropertyName
		swiftTypeName := model.SwiftTypeName
		proxyName := model.GoName + "TableProxy"
		g.P("\t", actorVisibility, "nonisolated var ", propertyName, ": ", proxyName, " { ", proxyName, "(actor: self) }")
		g.P("\tfileprivate func _", propertyName, "Initialize() throws { try withDatabase { try CRUD($0).", propertyName, ".initialize() } }")
		g.P("\tfileprivate func _", propertyName, "Select(where whereClause: String, arguments: [SQLiteBindValue]) throws -> [", model.RowTypeName, "] { try withDatabase { try CRUD($0).", propertyName, ".select(where: whereClause, arguments: arguments) } }")
		g.P("\tfileprivate func _", propertyName, "Insert(_ data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".insert(data) } }")
		if model.AllowCustomIDInsert {
			g.P("\tfileprivate func _", propertyName, "InsertWithID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".insertWithID(id, data: data) } }")
		}
		g.P("\tfileprivate func _", propertyName, "UpdateByID(_ id: String, data: ", swiftTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".updateByID(id, data: data) } }")
		g.P("\tfileprivate func _", propertyName, "UpdateRow(_ row: ", model.RowTypeName, ") throws -> ", model.RowTypeName, " { try withDatabase { try CRUD($0).", propertyName, ".updateRow(row) } }")
		g.P("\tfileprivate func _", propertyName, "DeleteByID(_ id: String) throws { try withDatabase { try CRUD($0).", propertyName, ".deleteByID(id) } }")
		g.P("\tfileprivate func _", propertyName, "DeleteRow(_ row: ", model.RowTypeName, ") throws { try withDatabase { try CRUD($0).", propertyName, ".deleteRow(row) } }")
		g.P("\tfileprivate func _", propertyName, "DrainUnknownRows() throws { try withDatabase { try CRUD($0).", propertyName, ".drainUnknownRows() } }")
		if model.ChangeListeners {
			g.P("\tfileprivate func _", propertyName, "Changes() throws -> AsyncStream<", model.GoName, "Change> { try withDatabase { CRUD($0).", propertyName, ".changes() } }")
		}
	}
	g.P("\t", actorVisibility, "func prepareJSONL(remote: String) throws -> PreparedJSONLExport { try withDatabase { try CRUD($0).prepareJSONL(remote: remote) } }")
	g.P("\t", actorVisibility, "func acknowledgeJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).acknowledgeJSONL(checkpoint) } }")
	g.P("\t", actorVisibility, "func discardJSONL(_ checkpoint: JSONLCheckpoint) throws { try withDatabase { try CRUD($0).discardJSONL(checkpoint) } }")
	g.P("\t", actorVisibility, "func writeJSONL(remote: String) throws -> String { try withDatabase { try CRUD($0).writeJSONL(remote: remote) } }")
	g.P("\t", actorVisibility, "func readJSONL(remote: String, stream: InputStream) throws { try withDatabase { try CRUD($0).readJSONL(remote: remote, stream: stream) } }")
	g.P("}")
}

func swiftMessageTypeNameForMessage(message *protogen.Message) string {
	names := []string{swiftSanitizeTypeName(string(message.Desc.Name()))}
	for parent := message.Desc.Parent(); ; parent = parent.Parent() {
		parentMessage, ok := parent.(protoreflect.MessageDescriptor)
		if !ok {
			break
		}
		names = append([]string{swiftSanitizeTypeName(string(parentMessage.Name()))}, names...)
	}
	prefix := swiftFileTypePrefix(message.Desc.ParentFile())
	names[0] = prefix + names[0]
	return strings.Join(names, ".")
}

func swiftFileTypePrefix(file protoreflect.FileDescriptor) string {
	options, ok := file.Options().(*descriptorpb.FileOptions)
	if ok && options.SwiftPrefix != nil {
		return options.GetSwiftPrefix()
	}
	packageName := string(file.Package())
	if packageName == "" {
		return ""
	}
	var result strings.Builder
	uppercaseNext := true
	for _, character := range packageName {
		switch character {
		case '_':
			uppercaseNext = true
		case '.':
			result.WriteRune('_')
			uppercaseNext = true
		default:
			if uppercaseNext {
				result.WriteString(strings.ToUpper(string(character)))
				uppercaseNext = false
			} else {
				result.WriteRune(character)
			}
		}
	}
	result.WriteRune('_')
	return result.String()
}

func swiftFieldName(protoName string) string {
	name := swiftLowerCamelCase(protoName)
	if swiftReservedFieldNames[name] {
		return name + "_p"
	}
	if swiftKeywords[name] {
		return "`" + name + "`"
	}
	return name
}

func swiftPresenceName(protoName string) string {
	baseName := swiftLowerCamelCase(protoName)
	name := "has" + swiftUpperCamelCase(protoName)
	if swiftReservedFieldNames[baseName] || hasUppercasePrefix(baseName, "has") || hasUppercasePrefix(baseName, "clear") {
		return name + "_p"
	}
	return name
}

func swiftLowerCamelCase(value string) string {
	upper := swiftUpperCamelCase(value)
	if upper == "" {
		return ""
	}
	for _, abbreviation := range []string{"HTTPS", "HTTP", "URL", "ID"} {
		if strings.HasPrefix(upper, abbreviation) {
			return strings.ToLower(abbreviation) + upper[len(abbreviation):]
		}
	}
	return strings.ToLower(upper[:1]) + upper[1:]
}

func swiftUpperCamelCase(value string) string {
	parts := strings.FieldsFunc(value, func(character rune) bool { return character == '_' })
	var result strings.Builder
	for _, part := range parts {
		lower := strings.ToLower(part)
		switch lower {
		case "id", "url", "http", "https":
			result.WriteString(strings.ToUpper(lower))
		default:
			if lower != "" {
				result.WriteString(strings.ToUpper(lower[:1]))
				result.WriteString(lower[1:])
			}
		}
	}
	return result.String()
}

func swiftSanitizeTypeName(value string) string {
	if swiftReservedTypeNames[value] || strings.HasSuffix(value, "Message") {
		return value + "Message"
	}
	return value
}

func hasUppercasePrefix(value, prefix string) bool {
	if !strings.HasPrefix(value, prefix) || len(value) == len(prefix) {
		return false
	}
	next := value[len(prefix)]
	return next >= 'A' && next <= 'Z'
}

var swiftKeywords = map[string]bool{
	"associatedtype": true, "class": true, "deinit": true, "enum": true, "extension": true,
	"fileprivate": true, "func": true, "import": true, "init": true, "inout": true,
	"internal": true, "let": true, "open": true, "operator": true, "private": true,
	"protocol": true, "public": true, "rethrows": true, "static": true, "struct": true,
	"subscript": true, "typealias": true, "var": true,
}

var swiftReservedFieldNames = map[string]bool{
	"debugDescription": true, "description": true, "dynamicType": true,
	"hashValue": true, "isInitialized": true, "unknownFields": true,
}

var swiftReservedTypeNames = map[string]bool{
	"Extensions": true, "Protocol": true, "Swift": true, "SwiftProtobuf": true,
	"Type": true, "Equatable": true, "Hashable": true, "Sendable": true,
	"decodeMessage": true, "description": true, "isInitialized": true,
	"protoMessageName": true, "traverse": true, "unknownFields": true,
}

func (e swiftEmitter) visibilityPrefix() string {
	if e.visibility == "" {
		return ""
	}
	return e.visibility + " "
}

func (e swiftEmitter) actorVisibilityPrefix() string {
	if e.actorVisibility == "" {
		return ""
	}
	return e.actorVisibility + " "
}

func (e swiftEmitter) sharedVisibilityPrefix() string {
	if e.visibility == swiftPublicVisibility || e.actorVisibility == swiftPublicVisibility {
		return swiftPublicVisibility + " "
	}
	if e.visibility != "" {
		return e.visibility + " "
	}
	return e.actorVisibilityPrefix()
}

func ParseSwiftGeneratorOptions(rawOptions map[string]string) (SwiftGeneratorOptions, error) {
	options := SwiftGeneratorOptions{Visibility: "Public"}
	for name, value := range rawOptions {
		switch name {
		case "Visibility":
			if err := validateSwiftVisibility(value); err != nil {
				return SwiftGeneratorOptions{}, err
			}
			options.Visibility = value
		case "PublicSynchronousAPI":
			publicSynchronousAPI, err := strconv.ParseBool(value)
			if err != nil {
				return SwiftGeneratorOptions{}, fmt.Errorf("parse PublicSynchronousAPI: %w", err)
			}
			options.PublicSynchronousAPI = publicSynchronousAPI
		default:
			return SwiftGeneratorOptions{}, fmt.Errorf("unsupported option %q", name)
		}
	}
	return options, nil
}

func validateSwiftVisibility(value string) error {
	switch value {
	case "Public", "Internal", "Package":
		return nil
	default:
		return fmt.Errorf("unsupported Visibility %q", value)
	}
}

func swiftVisibilityKeyword(value string) string {
	switch value {
	case "Public":
		return swiftPublicVisibility
	case "Internal":
		return "internal"
	case "Package":
		return "package"
	default:
		return ""
	}
}
